### ISSUE TITLE
v.14.4 PopoverMenu with default props won't open on click

### ISSUE THREAD

**Issue by bdares** [instructure/instructure-ui#1]
Can repro directly on demo site [here](http://instructure.github.io/instructure-ui/#PopoverMenu) - close the menu and attempt to re-open it.

When I render:

```
<PopoverMenu label={ <span>Foo</span> }>
  <MenuItem><Link onClick={console.log}>MENU</Link></MenuItem>
</PopoverMenu>
```

I end up with a menu button as expected.  Clicking on it does not toggle the visibility state of the popover.

After inspection, it appears that this is the reason:

* https://github.com/instructure/instructure-ui/blob/v0.14.4/lib/util/OverlayTrigger.js#L214
* https://github.com/instructure/instructure-ui/blob/v0.14.4/lib/util/OverlayTrigger.js#L228

When the button is clicked, it fires the `focus` event first, then the `click` event (at least on Chrome and Safari browsers).  

Since the menu is initially not visible, the [`focus`](https://github.com/instructure/instructure-ui/blob/v0.14.4/lib/util/OverlayTrigger.js#L134) handler will end up calling `this.toggle()`, which will set `show` to `true` (by calling the passed-in `onToggle` property function).

Then, the `click` event handler fires, invoking `toggle()`, re-hiding the menu immediately.

**Comment by junyper** [comment]
I think this is fixed in v0.15.0
