### ISSUE TITLE
Replace shortid with nanoid

### ISSUE THREAD

**Issue by killbillsbor** [instructure/instructure-ui#10]
Hi! Your project looks awesome!

I found a way how to make it a little bit better: please consider replacing `shortid` with [`nanoid`](https://github.com/ai/nanoid). There are no significant changes for users, but there are some nice improvements:

- `shortid` is not maintained anymore (and issue tracker has many important issues);
- `nanoid` is just [179 bytes](https://github.com/ai/nanoid/blob/master/package.json#L64-L67). shortid is two times larger (about 0.5 KB).
- Also, `nanoid` is [10x times faster](https://github.com/ai/nanoid#benchmark) than `shortid`.

What do you think about this @junyper @personable?

Thanks!

**Comment by junyper** [comment]
This looks like spam.

**Comment by junyper** [comment]
Sorry @killbillsbor. The content of your pull request was so similar to a pull request on our instructure-icons project that I thought it was spam. I'll look into this more.

**Comment by killbillsbor** [comment]
Glad to hear, @junyper! That PR was made by my teammate :) I'm junior developer and trying to help him. Thanks!

**Comment by arlodesign** [comment]
https://github.com/instructure/instructure-ui/pull/11#issuecomment-378026793
