### ISSUE TITLE
Discrepancies in InstructureIcon font glyphs: results don't match documentation

### ISSUE THREAD

**Issue by JimWeinrich** [instructure/instructure-ui#101]
In the documentation at <instructure.design/#icons-font>, there is a list showing the glyphs for the fonts **InstructureIcons-Line** and **InstructureIcons-Solid**. The hex values corresponding to each character don't match the results I get when I use them in the html code for my Canvas pages:

- From the beginning (hex EA01) up through EB05, everything is fine. Everything matches.

- At EB06, the documentations says the name of the character is "sort", and a glyph is shown that consists of two arrows (up and down). When I use this character on a Canvas page, however, the glyph that actually appears is the "speed-grader" icon, which the documentation says has a hex code of EB07. This one-off discrepancy holds true for the rest of the list, all the way through EB4A/EB4B.

Here is an example of some code that has the problem. According to the documentation, the "syllabus" icon's hex is EB11, but when I put that value into the HTML it gets transformed into a missing-character glyph -- which is expected. Then when I exit HTML and Edit mode and go back to the page as it would be seen by students, it shows up as the wrong icon. In order to get the correct "syllabus" icon to appear, I have to enter a hex code of EB10 (which shows up below as a box consisting of closely spaced horizontal lines):

[Sorry... all of the html was removed except for the odd character. Here's a version that I hope will survive to make the situation clear. The version you can see has some errors, i.e., omitted quote marks and extra spaces:]

<  span style=font: 2rem instructureIcons-Line;  >    < / span >

<span style="font: 2rem InstructureIcons-Line;"></span>

This same behavior happens at three different schools that use Canvas, so I think it is probably a mistake or a bug, rather than a school not updating its Canvas files correctly.

**Comment by HerrTopi** [comment]
Please provide us with your config and used version of InstructureUI.
