### ISSUE TITLE
Wrong Typescript typehints for TreeBrowser component icon props

### ISSUE THREAD

**Issue by horo42** [instructure/instructure-ui#1016]
### Background Information

**Package Version(s)**: 8.24.2

**Browser**: Chrome

**OS:** MacOS 12.4

**Device:** MacOS 12.4

**Component**: TreeBrowser

### Describe the Bug

The following props do not describe the expected props correctly:

https://github.com/instructure/instructure-ui/blob/6db128225d28aabea20ff45839f3a29730842596/packages/ui-tree-browser/src/TreeBrowser/props.ts#L110-L114

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/5323731/169711945-d536f85e-d76e-4997-afd3-c706a232b39b.png">

If I follow the type information:

<img width="286" alt="image" src="https://user-images.githubusercontent.com/5323731/169711926-fe5928fd-6718-4cdf-b4a8-f4721c8dca7c.png">
<img width="590" alt="image" src="https://user-images.githubusercontent.com/5323731/169711901-64ab20a6-dd17-485f-b46b-d7a5199d06ea.png">

### Steps To Reproduce

Create the following component in a project with Typescript enabled:
```
<TreeBrowser
    items={[]}
    collections={{}}
    collectionIcon={IconFolderLine}
/>
```

### Expected Behavior

I suggest using React.ComponentType or React.ElementType if strings like "div" should be accepted.

### Additional Information

**Current Workaround(s):** I'm using `collectionIcon={IconFolderLine as any}` as a workaround.

**Are you willing to submit a PR to fix?**
- [x] Yes, I'm willing to submit a PR

**Requested Priority:** low

**Comment by matyasf** [comment]
React 18 support is currently in PR https://github.com/instructure/instructure-ui/pull/1054 and will be released shortly that will fix this issue and you dont need to cast to `any`
