### ISSUE TITLE
Failed to install: ui-prop-types not found

### ISSUE THREAD

**Issue by SimonVanherweghe** [instructure/instructure-ui#1023]
### Background Information

**Package Version(s)**:
@instructure/ui 8.24.4

**OS:**
Max OS 12.3.1

using npm@8.3.0
using node@v16.13.1

**Device:**
MacBook Pro (16-inch, 2019)

### Describe the Bug
Unable to install the package.

``` bash
npm i @instructure/ui
npm WARN ERESOLVE overriding peer dependency
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@instructure/ui-prop-types/-/ui-prop-types-8.24.4.tgz - Not found
npm ERR! 404 
npm ERR! 404  '@instructure/ui-prop-types@https://registry.npmjs.org/@instructure/ui-prop-types/-/ui-prop-types-8.24.4.tgz' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

### Steps To Reproduce
- add the package in the package.json -> bug
- try to install with npm -> bug
- try to install with yarn -> bug

### Expected Behavior
Be able to install the package

**Requested Priority:**
High

**Comment by Brailor** [comment]
Hi @SimonVanherweghe!

We fixed this issue in a new release: https://github.com/instructure/instructure-ui/pull/1024

Can you try it out with the new version? (8.24.5)

**Comment by SimonVanherweghe** [comment]
Yes, mark as done!

Thanks
