### ISSUE TITLE
Can you help me to add id and custom class to component

### ISSUE THREAD

**Issue by thamsrang** [instructure/instructure-ui#104]
Hi,
I trying to add id and custom className to component. But its not working 

```
<Alert id="alertId" className="customAlertWarning"
        variant="warning"
        renderCloseButtonLabel="Close"
        margin="small"
        transition="fade"
      >
        Sample success alert text. I will close w/o a transition out if you close me
      </Alert>
```

**Comment by chrisguerrero** [comment]
Hello @thamsrang, we don't currently support passing the className prop through for applying custom styles. This is something we're exploring for a future release. Many of our components do support passing the `id` prop through, but it appears `Alert` does not. Can you help me understand your use case here a bit more?
