### ISSUE TITLE
Switch theme after rendering components

### ISSUE THREAD

**Issue by buckett** [instructure/instructure-ui#105]
I've got a LTI tool using Instructure UI components and as part of the LTI launch I can know if the user has requested to have a high contrast theme ( https://canvas.instructure.com/doc/api/file.tools_variable_substitutions.html `Canvas.user.prefersHighContrast` ), however as I am using React and doing all the rendering client side I load the page and then make an XHR request to load the data sent in the LTI launch, at this point I am already displaying a progress indicator and am using the standard Canvas theme. After the XHR request completes if the user requested high contrast I'd like to switch to the Canvas High Contrast theme, however this doesn't seem to be possible.

Has anyone found a solution to this?

**Comment by chrisguerrero** [comment]
Hey @buckett, you should be able to use [ApplyTheme](https://instructure.design/#ApplyTheme) to dynamically apply the high contrast theme. [Check out this example](https://codesandbox.io/s/theme-switcher-tzjy4) I put together - hope it helps!

**Comment by buckett** [comment]
Thanks, really helpful to show I was on the right track, I was trying that and sort-of getting the expected results, but my problem was that I'd loaded the theme overrides for the canvas theme and when switching to the high contrast theme they were still being applied which I wasn't expecting.

I think this fix for this is to say the theme is `immutable` with it's the high contrast theme:
``` 
<ApplyTheme theme={this.state.theme} immutable={this.props.highContrast}>
        {this.props.children}
</ApplyTheme>
```
This way when the user has selected high contrast in Canvas they get the same behaviour in our tool.

**Comment by buckett** [comment]
Nope, I've still got strange issues with theming.

https://codesandbox.io/s/theme-switcher-forked-7zzlz

I've added a button to your example and the theme for the button seems to lag changes on the theme selector.

**Comment by matyasf** [comment]
Hi

We are migrating to themeabe for the next version of InstUI (v8.0), this will likely solve your issue. If it still persist please comment here. The release is planned sometime in April 2021

**Comment by buckett** [comment]
@matyasf Thanks for the update, am I right in thinking your going to be using https://emotion.sh/docs/theming for theming for in  version 8.0 ?

**Comment by matyasf** [comment]
Yes, exactly

**Comment by ke1k0** [comment]
Hi @buckett! We released v8 today, featuring the new [emotion](https://instructure.design/#emotion) theming solution. Here is the [upgrade guide](https://instructure.design/#v8-upgrade-guide) from v7 to v8. I'm closing this ticket now, but feel free to contact us, if you have any questions :)
