### ISSUE TITLE
Pagination.Page should support the screenReaderLabel property

### ISSUE THREAD

**Issue by mpellicer** [instructure/instructure-ui#106]
Our testers reported accessibility issues related to this component, it renders a button without a proper text for screen readers.

IconButton supports screenReaderLabel while Pagination.Page does not support it.

Example (Wrong):
<Pagination.Page>
  <IconMoveStartSolid />
</Pagination.Page>

This renders a button without proper text for screen readers.

Example (Right):
<Pagination.Page>
    <IconButton screenReaderLabel="Move to the first page"><IconMoveStartSolid /> </IconButton>
</Pagination.Page>

This renders a button inside a button, works fine but having a button inside a button is not desirable.

Example (Desirable):
<Pagination.Page screenReaderLabel="Move to the first page">
    <IconMoveStartSolid />
</Pagination.Page>

This may renders a button with a proper text for screen readers.

**Comment by mpellicer** [comment]
Not sure @ke1k0 sorry, I reported this in August 2020 and I remember resolving it using a workaround :(

**Comment by ke1k0** [comment]
May I close this ticket then?

**Comment by mpellicer** [comment]
Yeah I think you can if you don't have the right information, I've checked the associated commits and I fixed it in August using a React workaround.

Thanks!

**Comment by ke1k0** [comment]
Just open a new ticket if you ever have problem with this again. :) Thanks!
