### ISSUE TITLE
ToggleGroup: background has no effect

### ISSUE THREAD

**Issue by rlorenzo** [instructure/instructure-ui#107]
We are using the ToggleGroup component and want to have a the parent ToggleGroup have a darker background than the part that it toggles.

That is possible in ToggleDetails using variant="filled".

We saw in the code examples for ToggleGroup that it has an prop for background="default". But changing that seems to do nothing. It also does not seem to be referenced in the implementation code here: https://github.com/instructure/instructure-ui/blob/master/packages/ui-toggle-details/src/ToggleGroup/index.js

Can we have the background prop be implemented so that we can color the background for the ToggleGroup? Or have a variant="filled" option like for ToggleDetails?

**Comment by chrisguerrero** [comment]
Hey @rlorenzo, you're correct - the ToggleGroup component does not accept a `background` property, and it appears it also does not support theming. I'm not sure why that's the case. Are you able to simply use the ToggleDetails component instead, or does ToggleGroup support additional functionality that you need?

**Comment by rlorenzo** [comment]
@chrisguerrero We wanted to have nested components and we thought that only ToggleGroup allowed us to do that. But our developer ended up being able to nest ToggleDetails just fine: https://github.com/ucla/lti-media-resources/blob/CANVAS-47-Display-available-Digital-audio-reserves/src/client/components/AdminPanel/MusicResListingsAlbumToggle.js#L35

Closing this as not needed.
