### ISSUE TITLE
Warning: [themeable] component styles require setting a 'dir' attribute on the HTML element.

### ISSUE THREAD

**Issue by rlorenzo** [instructure/instructure-ui#108]
We get this warning "Warning: [themeable] component styles require setting a 'dir' attribute on the HTML element." when running jest tests for our project. 

See https://github.com/ucla/lti-media-resources/pull/21/checks?check_run_id=1009553467#step:8:18

I see the warning is coming from https://github.com/instructure/instructure-ui/blob/master/packages/ui-themeable/src/setTextDirection.js#L42

Also, it appears when using the app in the Browser's console. 

How do we fix this or set it for all our components by default?

**Comment by chrisguerrero** [comment]
@rlorenzo You should be able to fix this by [setting a `dir` value at the document level](https://www.w3.org/International/questions/qa-html-dir#documentlevel). Because InstUI supports text bi-directionality, the theming engine expects this value to be set.

**Comment by rlorenzo** [comment]
Thanks, I see that we need to add it like:

<html lang="en" dir="ltr">

**Comment by rlorenzo** [comment]
@chrisguerrero So adding it to the html tag works when running our app now. It doesn't produce the warning. But when running a Jest test it doesn't have access to the top level html tag and still creating a warning.

Any thoughts how to get the warning to disappear from our tests?

**Comment by chrisguerrero** [comment]
@rlorenzo You should be able to add some setup logic using `beforeEach` to append the `dir` attribute to the document, e.g.: 

```
document.documentElement.setAttribute('dir', 'ltr')
```
