### ISSUE TITLE
A very minor alignment issue with <InlineList>

### ISSUE THREAD

**Issue by cvkline** [instructure/instructure-ui#1116]
### Background Information

One component in Canvas uses an InlineList and one of the elements is slightly vertically misaligned from the others. This is a very minor issue.

**Package Version(s)**:
ui-list 7.14

**Browser**:
Only tested in Chrome 106

**Component**:
<InlineList>

### Describe the Bug
We have a component that uses an InlineList (with delimiter="pipe") and while it works fine and looks _mostly_ okay, there is a very slight vertical alignment issue that seems to be caused by one of the list items being a <Link> with a renderIcon. See the attached screenshot, the middle item and its following pipe separator are slightly lower than the rest of the list. 

### Expected Behavior
All list items (and their separators) should be aligned vertically to the same degree.

### Additional Information

**Current Workaround(s):**

**Screenshots:**
![Screen Shot 2022-10-18 at 11 03 45 AM](https://user-images.githubusercontent.com/6576592/196513130-1c727979-34e5-4b59-baf0-448e0ec7a758.png)

**Products Affected:**
Canvas-LMS

**Are you willing to submit a PR to fix?**
- [ ] Yes, I'm willing to submit a PR

**Requested Priority:**
Low

**Comment by ke1k0** [comment]
Hi @cvkline ! Can you please check in the dev toolbar if setting the `vertical-align` of the`<li>` elements  to "baseline" fixes your issue? My first idea is to expose this as a themeable variable, so it is settable on the user's side.

For most cases the middle align should work fine, and I'm afraid it would be breaking change to just simply set it to "baseline" now.

Also, if the vertical alignment doesn't seem to fix your issue, can you please send a code sample? Thanks!

![image](https://user-images.githubusercontent.com/11446033/196650526-8e9189bd-b1d4-4a16-a052-8e2cf18480bf.png)

**Comment by ke1k0** [comment]
Hi @cvkline ! Just wanted to ask for an update: does changing the vertical align fix your problem? Is it still an issue or can I close the ticket? Thanks!
