### ISSUE TITLE
Modal doesn't always re-open

### ISSUE THREAD

**Issue by buckett** [instructure/instructure-ui#1173]
### Background Information

**Package Version(s)**:
8.35.0

**Browser**:
Chrome Version 110.0.5481.177 (Official Build) (arm64)

**OS:**
13.1 (22C65)

**Device:**
MacBook

**Component**:
Modal

### Describe the Bug
If a `<Modal>` component is closed (setting `open` prop to false) and then opened again (setting `open` prop to true) before the closing transition has completed the modal doesn't re-open and remains closed.

### Steps To Reproduce

Test with this example component:
```javascript
import { Modal } from '@instructure/ui-modal'
import { Button } from '@instructure/ui-buttons'
import { useEffect, useState } from 'react'

const ModalTest = () => {
  const [open, setOpen] = useState(true)
  useEffect(() => {
    if (!open){
      // Delay the re-opening
      setTimeout(() => {
        setOpen(true)
        console.log('Re-opened')
      }, 10)
    }
  })
  return <Modal label='test' open={open}>
    <Modal.Header>Open Bug</Modal.Header>
    <Modal.Body>Some stuff here</Modal.Body>
    <Modal.Footer>
      <Button onClick={() => {
        setOpen(false)
        console.log('Closed')
      }
      }>Close</Button>
    </Modal.Footer>
  </Modal>
}

export default ModalTest
```

- Click on the close button and the modal is still displayed.
- Click on the close button again and the modal this time disappears and doesn't appear again
- Click on the location that the modal button was previously rendered and it is in-fact still responding to events.

If you change the time inside the `setTimeout()` to 1000 then everything works as expected.

### Expected Behavior

When you click on Close it should attempt to close, but be re-opened and be repeatable no matter what the timeout.

### Additional Information

**Current Workaround(s):**

Ensure that the modal has finished it's transitions before opening it.

**Comment by buckett** [comment]
This was found when using a Modal to prompt for credentials, when the user entered incorrect credentials the dialogue was re-opened, if the remote server was slow it would re-open fine, if the response came back quickly nothing would be displayed.

**Comment by Brailor** [comment]
Hi @buckett!
Thanks for the issue report, we will investigate this problem and get back to you as soon as we can!

**Comment by matyasf** [comment]
related PR: https://github.com/instructure/instructure-ui/pull/1183

**Comment by matyasf** [comment]
This is fixed, we'll close this issue. Message us if you still see this problem!

**Comment by buckett** [comment]
Sorry for taking so long to get back to you, it's working a treat for me now thanks.
