### ISSUE TITLE
Flex component - add gap attribute

### ISSUE THREAD

**Issue by raman-savitski-instructure** [instructure/instructure-ui#1190]
### Context

Flex

### Summary

Please add `gap` attribute to flex component.

### Justification

This is standard css flex property, which can be very useful in some use cases.

### Additional Details

https://developer.mozilla.org/en-US/docs/Web/CSS/gap

**Comment by ke1k0** [comment]
Hi @raman-savitski-instructure ! Thank you for the request, I'll make a Jira ticket from it :)

**Comment by ke1k0** [comment]
Hi @raman-savitski-instructure ! Is this new prop something you need now for a new feature, or just a nice-to-have? Just asking so I can set the priority for the ticket :)

**Comment by raman-savitski-instructure** [comment]
Nice to have, this will simplify some use-cases. So I don't need to specify left-right margins for every Flex.Item

**Comment by matyasf** [comment]
hi! We have added the `gap` prop, you can use it from InstUI 8.38.0
