### ISSUE TITLE
SimpleSelect value contains the selected option 'label' value, not the attribute value

### ISSUE THREAD

**Issue by SimonVanherweghe** [instructure/instructure-ui#1210]
### Question
I noticed the value of the selected option in the DOM (and the value that is posted in the end) is the label of the option, not the value attribute.
Is this a bug or necessary for the functionality of the component?

### Code Sample
https://codesandbox.io/s/simple-select-value-ne175g
Select an option, submit the form, and look in the inspector to the payload. I'm expecting 22, but I'm getting "Bar" in this case
![simpleselect](https://github.com/instructure/instructure-ui/assets/655147/609edae9-1181-4537-8560-f16ee4525805)

### Additional Details
In the [simple select docs](https://instructure.design/#SimpleSelect) there is the following:

> ...that closely parallels the functionality of standard HTML `<select>` elements. 

On [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option), for the value attribute of the label:

> The content of this attribute represents the value to be submitted with the form, should this option be selected.

So I'm wondering, why is this behaviour different?

I'm using Instructure-ui in a Remix project, which uses basic web standards as much as possible. This implies using the values of the form fields. So this component isn't usable. I think the same problem will occur when using React router v6

**Comment by matyasf** [comment]
hi!

Sorry for the late reply, its different for technical reasons. InstUI uses a native `input` for `SimpleSelect` and `Select`'s text display which does not have a different value for its value and input. 
We do not suggest to use a HTML form when using these components, rather listen to its change events, update some internal state and send data to the backend with some API call.

**Comment by matyasf** [comment]
We might fix this with a workaround (e.g. making a hidden `input` in a next major version)
