### ISSUE TITLE
Focus callback is called twice for each event in <TextInput>

### ISSUE THREAD

**Issue by cvkline** [instructure/instructure-ui#1233]
### Background Information

**Package Version(s)**:
ui-text-input  v8.38

**Browser**:
At least Safari and Chrome, I didn't test extensively

**OS:**
MacOS 13.4 and also whatever environment the Canvas Jenkins builds run in

**Component**:
TextInput

### Describe the Bug
If the onFocus prop is used to provide a callback function when the input field is focused, the callback is called TWICE for each focus event.

### Steps To Reproduce
Go to the instructure.design documentation page for TextInput and in the first example (the John Doe one), edit the live code to read:

    <TextInput
      renderLabel="Name"
      placeholder="Doe, John Doe"
      onChange={(event, value) => { console.log(value) }}
      onFocus={e => { console.info('FOCUS') }}
      onBlur={e => { console.info('BLUR') }}
    />

Then open the browser console and click in and out of the input field. You will see two occurrences of "FOCUS" each time you click in, and only one (as expected) "BLUR" when you click out.

### Expected Behavior
The focus and blur callbacks should be called only once per relevant event.

**Comment by matyasf** [comment]
Fix in https://github.com/instructure/instructure-ui/pull/1234

**Comment by matyasf** [comment]
Does it work? Can we close this ticket?
