### ISSUE TITLE
[ui-select,ui-simple-select] Keyboard navigation broken after scrolling

### ISSUE THREAD

**Issue by AlexKichkailo** [instructure/instructure-ui#1244]
### Background Information

**Package Version(s)**:
ui-select ui-simple-select

**Browser**:
 Chrome (All Versions)

**OS:**
iOS 13.4.1

**Device:**
Mac Pro

**Component**:
Select, SimpleSelect

### Describe the Bug
Keyboard navigation gets broken after scrolling.

### Steps To Reproduce
    1. Go to[ 'Simple Select examples'](https://instructure.design/#SimpleSelect)
    2. Find the example for the Controller component (the  important thing here is that there should be more than 8 options in the select component to replicate the issue)
    3. Click the component in the example so it shows options
    4. Scroll down to `Illinois`, then scroll up to `Alaska`
    5. Now try to go down to `Illinois` via keyboard. Strange things will happen after `Delaware`.
    6. Instead of highlighting `District of Columbia`, it highlights an option above `Delaware`. 

### Expected Behavior
Keyboard navigation works as expected after using the mouse scroll. 

### Screenshots
See recorded video
https://github.com/instructure/instructure-ui/assets/4992307/69a573af-44fb-48be-a362-3e764e99f611

### Additional Information

**Current Workaround(s):**
none

**Products Affected:**
All products that use Select, SimpleSelect and probably selectable.

**Requested Priority:**
Normal

**Comment by HerrTopi** [comment]
Hi! Thanks for the report!
The issue isn't related to scrolling, rather it is caused by the position of the cursor. When you reach the bottom of the select with the keyboard navigation, it redraws the list and then jumps the highlighted node to the cursor's place. If you move the cursor out of the list, it will work as expected.
It is still a bug, so I'll see what I can do about it!

**Comment by matyasf** [comment]
Tracked internally in INSTUI-3819

**Comment by HerrTopi** [comment]
After consideration, this is a small bug, but in order to fix it , we'd need to rewrite substantial parts of the select and underlaying components. 

We have a ticket about this, but its not on our roadmap in the near future. If we get around to do it, I'll comment to this ticket
