### ISSUE TITLE
SimpleSelect doesn't update `value` attribute on form element

### ISSUE THREAD

**Issue by buckett** [instructure/instructure-ui#1247]
### Background Information

**Package Version(s)**:

8.39.0 ui-simple-select

**Browser**:

Chrome 115

**OS:**

Mac OS

**Component**:

SimpleSelect

### Describe the Bug
The form element behind `<SimpleSelect>` doesn't get correctly updated to contain the value of the selected item, instead the title of the selected item is used.

### Steps To Reproduce
```jsx
<SimpleSelect renderLabel="Uncontrolled Select" onBlur={e=>console.log(e.target.value)}>
  <SimpleSelect.Option id="foo" value="foo">
    Foo
  </SimpleSelect.Option>
  <SimpleSelect.Option id="bar" value="bar">
    Bar
  </SimpleSelect.Option>
  <SimpleSelect.Option id="baz" value="baz">
    Baz
  </SimpleSelect.Option>
</SimpleSelect>
```

### Expected Behavior
The console should see logged values of foo, bar or baz.

### Additional Information

**Current Workaround(s):**
Use `onChange` which has the value passed into it directly.

**Requested Priority:**
Low

**Comment by buckett** [comment]
Looks like #1210 reported the same issue, so I'm guessing this won't be fixed.

**Comment by matyasf** [comment]
Yep, its a duplicate. Still its useful input for us, if more people need this we will raise its priority. Thanks for the report!

**Comment by cmurtaugh** [comment]
It'd be helpful to add something to the documentation to warn folks that `<SimpleSelect>` does _not_ closely parallel the HTML `<select>` element in this crucial aspect.
