### ISSUE TITLE
v7 stacked, sortable table uses ids instead of header names in the "sort by" dropdown

### ISSUE THREAD

**Issue by jaredcrystal** [instructure/instructure-ui#1269]
### Background Information

**Package Version(s)**: 
ui-table v7.22.1

**Component**:
Table

### Describe the Bug

Using v7, a stacked, sortable table uses ids instead of header names in the "sort by" dropdown/combobox (while v8 correctly uses header names).

### Steps To Reproduce
In the v7 docs, the ids and header names are identical, which masks the bug: https://instructure.design/v7/#Table

Here I've modified one of the ids to make the issue obvious (pictured below in the "screenshots" section): https://codepen.io/jcrystal/pen/NWeNddp?editors=0010

### Expected Behavior
Header names (not ids) are used in the "sort by" dropdown when using a stackable, sortable table for v7 the way they are for v8.
The v8 docs are handling it correctly: https://instructure.design/#Table

### Screenshots
<img width="1792" alt="image" src="https://github.com/instructure/instructure-ui/assets/14153009/acda50a3-132d-4b43-8c31-174286e1b0f0">

### Additional Information

**Current Workaround(s):**
match the header names and ids to be identical

**Products Affected:**
New Quizzes (on v7) is implementing a stackable, sortable table, which has run into this issue.

**Requested Priority:**
Normal

**Comment by matyasf** [comment]
tracked internally in INSTUI-3845
