### ISSUE TITLE
SimpleSelect KO and SR opening issues

### ISSUE THREAD

**Issue by akos0horvath** [instructure/instructure-ui#1286]
### Background Information

**Package Version(s)**:
ui-simple-select v8.43.1

**Browser**:
Chrome

**OS:**
Win10, Win11, MacOS Ventura

**Device:**
Lenovo Thinkpad, Macbook Pro

**Component**:
SimpleSelect

**Screen Reader:**
NVDA, VoiceOver

### Describe the Issue
SimpleSelect does not open with 'space' key on Win10 & Win11 when NVDA is on.
SimpleSelect does not open with control+option+space with Chrome with VoiceOver on Mac.
Probably two separate issues.

### Steps To Reproduce
On Windows:
1. Turn on NVDA
2. Open Chrome
3. Go to https://instructure.design/#SimpleSelect
4. Press space on a SimpleSelect component => nothing happens.
5. (turn off NVDA, press space => it opens the dropdown as expected)

On Mac:
1. Turn on VoiceOver
2. Open Chrome
3. Go to https://instructure.design/#SimpleSelect
4. Press control+option+space on a SimpleSelect component => nothing happens.

### Expected Behavior
SimpleSelect should open on 'space' key on Windows regardless of NVDA is enabled or not.
SimpleSelect should open on control+option+space with VoiceOver with Chrome (it works with Safari).

### Additional Information

**Requested Priority:**
High

**Comment by matyasf** [comment]
Thanks for the report, we are looking into it

**Comment by joyenjoyer** [comment]
Hey @akos0horvath! The [latest release](https://github.com/instructure/instructure-ui/releases/tag/v8.44.0)  contains the fix for this issue. Let us know if there is any issue still.

**Comment by akos0horvath** [comment]
thank you @joyenjoyer , all good now!
