### ISSUE TITLE
Override default theme for Select

### ISSUE THREAD

**Issue by micabe** [instructure/instructure-ui#13]
Looks like Select is not themeable ?
Is this sthg you will look at  in the near future ?

**Comment by junyper** [comment]
@micabe it is possible to theme Select, but admittedly not very straightforward or well documented. We are planning to refactor it to make it much easier (likely in the 6.0 release), but I think this would work for now:

```
import SelectField from '@instructure/ui-forms/lib/components/Select/SelectField'
import SelectOptionsList from '@instructure/ui-forms/lib/components/Select/SelectOptionsList'
import SelectMultiple from '@instructure/ui-forms/lib/components/Select/SelectMultiple'

<ApplyTheme
  theme={{
          [SelectField.theme]: {
            labelColor: 'red'
          },
          [SelectOptionsList.theme]: {
            labelColor: 'blue'
          },
          [SelectMultiple.theme]: {
            tagTopMargin: '2rem'
          }
  }}
>
  <Select ... />
</ApplyTheme>
```

The theme variables for SelectField, SelectOptionsList, and SelectMultiple are documented here:

https://instructure.design/#Select

(Note: you have to click on the tab for each of those components to see the props and theme variables).
