### ISSUE TITLE
Option to make the DateInput component "clearable"

### ISSUE THREAD

**Issue by csmaty** [instructure/instructure-ui#1322]
### Context
When a date input field is optional, users should be able to easily remove a date without having to manually delete the value of the input.

### Summary
`ui-date-input` / `ui-date-time-input`

I would like to request to introduce an option to make `<DateInput />` clearable. The objective would be to provide a way for the users to clear the date value with a single click.
This doesn't necessarily need to be the default behaviour when the input is not required, but would be nice to have a `clearable` property or a similar setting.

Ways to achieve this could be:

- Adding an inline ✖️ button within the text input.
- Introducing a separate clear button in the `<Calendar />` component, similar to the native [date picker](https://show-picker.glitch.me/demo.html).
- Maybe adding the possibility for users to deselect the current date selection in the calendar

**Comment by matyasf** [comment]
hi!

Thanks for the recommendation, we will forward and discuss it with the design team

**Comment by HerrTopi** [comment]
We run it through the designers, as of right now, we don't plan to implement a feature like this. Nevertheless, it can be implemented in a case-by-case manner
