### ISSUE TITLE
[ui-select] removing an option from Multiple Select should have some announcement

### ISSUE THREAD

**Issue by akos0horvath** [instructure/instructure-ui#1334]
### Background Information

**Package Version(s)**:
ui-select v8.46.1

**Browser**:
All

**OS:**
All

**Device:**
All

**Component**:
Select

**Screen Reader:**
All

### Describe the Issue
Removing an option from a Multiple Select doesn't have any indication for SR users, and it would be a nice improvement if an announcement was made when the action happens.

### Steps To Reproduce
1. Select an option from a `Select` component with `multiple` prop passed to it
2. Remove that option by mouse or KO
3. The action happens but only with visual confirmation, SR users are not notified

### Expected Behavior
SR users should have some confirmation that the option was removed

### Additional Information

**Current Workaround(s):**
Everyone can implement something on their side of the code, but it would be the best if this was a built-in funcionality.

**Products Affected:**

**Are you willing to submit a PR to fix?**
- [ ] Yes, I'm willing to submit a PR

**Requested Priority:**
Normal

**Comment by HerrTopi** [comment]
Hi! Sorry for the long delayed response. We somehow missed your issue. 
This is a good suggestion, we'll get to it in time and let you know

**Comment by balzss** [comment]
Hi @akos0horvath, I looked into it and currently with the multiselect component we have an example in our docs page on how to configure it: https://instructure.design/#Select/#Highlighting%20and%20selecting%20options

This example have some solutions for screenreaders: using an `Alert` tag with a `screenReaderOnly` prop and changing its value via a state variable. This could be extended to also include the announcement of a tag's removal without an API change. This way users don't have to invent a new solution, just copy ours.

Ideally the `Select` component would need much less configuration out of the box and we plan to revamp it sometime but it is not on our current roadmap. 

I'll link the PR with the updated example here when it's ready.
