### ISSUE TITLE
SideNavBar inherits unwanted global styles

### ISSUE THREAD

**Issue by aaronshaf** [instructure/instructure-ui#1340]
### Background Information

**Package Version(s)**:
8.x

**Browser**:
Chrome

**OS:**
BeOS

**Device:**
Palm Pilot

**Component**:
SideNavBar

### Describe the Bug
When using SideNavBar in Canvas the nav bar items inherit unwanted global styles that seem related to the global a/anchor tag. This relates to color and text-decoration (underline). 

### Expected Behavior
If possible SideNavBar items should not inherit global styles.

**Comment by aaronshaf** [comment]
<img width="79" alt="image" src="https://github.com/instructure/instructure-ui/assets/122654/87d5eaba-73cc-446e-9df9-6028e40d885e">

**Comment by balzss** [comment]
fix in #1352
