### ISSUE TITLE
Increase font weight of SideNavBar items to 400

### ISSUE THREAD

**Issue by aaronshaf** [instructure/instructure-ui#1345]
This increases visual parity with the font weight of current nav items in Canvas LMS.

Before:

<img width="84" alt="image" src="https://github.com/instructure/instructure-ui/assets/122654/2ff6b422-2aaf-4b6b-a53a-943f011ed354">

After:

<img width="83" alt="image" src="https://github.com/instructure/instructure-ui/assets/122654/ad750e1a-1494-4532-ae52-e5480e796e9e">

It also makes the text more accessible.

**Comment by balzss** [comment]
fixed in #1359
