### ISSUE TITLE
SideNavBar item style improvements

### ISSUE THREAD

**Issue by aaronshaf** [instructure/instructure-ui#1347]
Please see this commit:

https://github.com/instructure/canvas-lms/commit/9cbfb3b8be6d3839aa2f958d3956ec27e8f5b435

We had to use a few styling workarounds. Can the SideNavBar component be updated to remove the need for some of them?

For visual parity with the old side nav bar in Canvas, items that are hovered should be set to:

`background-color: rgba(0, 0, 0, 0.2);`

With a transition value of:

`transition: background-color 0.3s, padding 0.3s;`

Please also support the equivalent of:

```
.sidenav-container a[data-selected="true"]:hover {
  color: var(--ic-brand-primary);
  background-color: var(--ic-brand-global-nav-menu-item__text-color);
}
```

**Comment by joyenjoyer** [comment]
It is fixed in #1378.
