### ISSUE TITLE
Remove ie11 specific polyfills from our webpack build

### ISSUE THREAD

**Issue by HerrTopi** [instructure/instructure-ui#136]
### Summary
Remove ie11 specific polyfills from our webpack build

### Justification
IE no longer supported

### Additional Details
We provide a lot of polyfills in `browserslist-config-instui/polyfills.js`. These are getting pulled into `ui-webpack-config` We should still export these as before, but we should remove them from our build.

Removing these may cause regressions in non ie11 browsers, this ticket will involve investigation to ensure that things break in ie11 only. That could be an extensive task as all components will need to be checked. We should work closely with QA to ensure no regressions.

**Comment by bestuiexperience** [comment]
I have an application that needs to support IE11. If I use the IE11 polyfill is there a way I can get this library to work with IE11?

**Comment by HerrTopi** [comment]
Thank you for using IntructureUI!

Unfortunately, IE11 is only supported until v6. We are now at v7 so as we are already dropped support since may. I would  say, you have to stay on v6. It is supported still with braking bug fixes, and security issues, but no more.
