### ISSUE TITLE
unordered list is numbered if nested inside ordered list

### ISSUE THREAD

**Issue by hart0554** [instructure/instructure-ui#1381]
### Background Information

**Package Version(s)**:
ui-list 8.49.0

**Browser**:
Chrome 119.0.6045.159
Safari 17.1

**OS:**
macos 14.1.1

**Device:**
Macbook Pro

**Component**:
List

### Describe the Bug
Unordered lists nested inside an ordered list are numbered following from the parent list

### Steps To Reproduce
In a component using @instructure/ui-list, create a simple nested list:
```
<List as="ol">
  <List.Item>Ordered List Item with sub items
    <List as="ul">
      <List.Item>Sub Item</List.Item>
      <List.Item>Another Sub Item</List.Item>
    </List>
  </List.Item>
  <List.Item>Ordered List without sub item</List.Item>
</List>
```
This results in a list that appears as such:
```
1. Ordered List Item with sub items
    &bull; 2. Sub Item
    &bull; 3. Another Sub Item
4. Ordered List without sub item
```

### Expected Behavior
Should see a list like
```
1. Ordered List Item with sub items
    &bull; Sub Item
    &bull; Another Sub Item
2. Ordered List without sub item
```

### Additional Information

**Current Workaround(s):**
I've attempted to use emotion's css property to override the `li::before` rules from here: https://github.com/instructure/instructure-ui/blob/8420ecef38edf7bcfa8a97f4d0506289bd342539/packages/ui-list/src/List/styles.ts#L58-L64
But have not been successful. For the time being I'm stuck not using the `<List>` component and just using `<ol>` and `<ul>` tags in my component.

**Are you willing to submit a PR to fix?**
- [x] Yes, I'm willing to submit a PR
If there's an easy way to use emotion to get around this that I am missing I will happily do that rather than submit a PR, but I've so far not been successful. A simple PR that changes 
https://github.com/instructure/instructure-ui/blob/master/packages/ui-list/src/List/styles.ts#L58 to use `'> li::before'` rather than just `'li::before'` as the selector should do it.

**Requested Priority:**
Normal

**Comment by joyenjoyer** [comment]
Hey @hart0554!

We are glad to receive this finding from you, we look into it tomorrow and get back to you.
