### ISSUE TITLE
Support for button groups

### ISSUE THREAD

**Issue by aaronshaf** [instructure/instructure-ui#1406]
One example use-case would be the calendar.
<img width="74" alt="image" src="https://github.com/instructure/instructure-ui/assets/122654/3ed010b6-4fb8-4f88-8c33-6942493f99af">

**Comment by joyenjoyer** [comment]
Thanks for the suggestion Aaron, I sent this to the designers.

**Comment by joyenjoyer** [comment]
@aaronshaf feedback from our designers: they welcome your suggestion and are happy about it. They put it on their backlog; they are working on a new Design Kit and when they get to brainstorming about new components they are going to do some research on this.
