### ISSUE TITLE
TopNavBarBrand deprecation warning

### ISSUE THREAD

**Issue by raman-savitski-instructure** [instructure/instructure-ui#1410]
### Background Information

**Package Version(s)**:
ui-top-nav-bar v8.51.0

**Browser**:
Chrome (All Versions)

**OS:**
MacOS

**Component**:
TopNavBar

### Describe the Bug
With the latest update (v8.51.0) I'm getting lots of console warnings:
`
Warning: [TopNavBarBrand] is deprecated and will be removed in version 9. Please use the updated TopNavBar design.
`

However I don't see any updates in documentation regarding this changes.

### Steps To Reproduce
Actually codesandbox examples from TopNavBar documentation page throws same warning.
For example: https://codesandbox.io/p/sandbox/wild-fog-4246rl

### Expected Behavior
Update documentation or remove warning.

**Requested Priority:**
Normal

**Comment by joyenjoyer** [comment]
Hey @raman-savitski-instructure! Thanks for the report, We will adjust the docs.
