### ISSUE TITLE
Replace CRA instructions in Quick Start with modern examples

### ISSUE THREAD

**Issue by aaronshaf** [instructure/instructure-ui#1415]
Create React App is no longer recommended in the modern React ecosystem. It is essentially replaced now with a setup like:

– Vite + React (Especially this one)
– rsbuild + React
– Remix
- Next.js

I would recommend instructions and working examples in those scenarios, and removing references to CRA.

Thanks fro all you do!

**Comment by HerrTopi** [comment]
Yeah, good point. We hope to do this in the near future, possibly this Q1
