### ISSUE TITLE
Cannot find module  '.\node_modules\@instructure\command-utils\node_modules\concurrently\bin\concurrently.js/package.json'

### ISSUE THREAD

**Issue by himanshudigikull** [instructure/instructure-ui#143]
Error: Cannot find module '.\node_modules\@instructure\command-utils\node_modules\concurrently\bin\concurrently.js/package.json'
Require stack:
- C:\Users\9hima\OneDrive\Documents\MyInstuiApp\node_modules\@instructure\command-utils\lib\index.js
- C:\Users\9hima\OneDrive\Documents\MyInstuiApp\node_modules\@instructure\ui-scripts\lib\build\webpack.js
- C:\Users\9hima\OneDrive\Documents\MyInstuiApp\node_modules\@instructure\ui-scripts\lib\build\index.js

**Comment by Brailor** [comment]
Hi, thanks for opening a ticket, however could you please re-open this issue with using our new issue templates?
