### ISSUE TITLE
No padding between Checkbox and it's messages

### ISSUE THREAD

**Issue by jzsfkzm** [instructure/instructure-ui#147]
### Background Information

**Package Version(s)**:
@instructure/ui v7.2.0

**Browser**:
Chrome

**OS:**
macOS 10.15.7

**Device:**
desktop computer

**Component**:
Checkbox

### Describe the Bug
Messages of the Checkbox component are too close to the checkbox itself.

### Steps To Reproduce
1. Render a Checkbox with a valid 'messages' prop added.
2. See the messages rendered are too close.

### Expected Behavior
Some space between would be nice.

### Screenshots
<img width="635" alt="Screen Shot 2020-10-19 at 14 21 07" src="https://user-images.githubusercontent.com/708113/96450926-2341e180-1217-11eb-94d1-086188c3505e.png">

### Additional Information

**Current Workaround(s):**
Local CSS hacks can fix it.

**Products Affected:**
SIStemic LTI tool

**Are you willing to submit a PR to fix?**
[ ] Yes, I'm willing to submit a PR

**Requested Priority:**
Normal

**Comment by ke1k0** [comment]
This change is implemented in the v8 release. https://github.com/instructure/instructure-ui/blob/v8.0.0/packages/ui-checkbox/CHANGELOG.md#800-2021-03-29
