### ISSUE TITLE
Plz to show imports on examples

### ISSUE THREAD

**Issue by tgroshon** [instructure/instructure-ui#16]
The documentation is _really, really good_; thank you for that!

One issue however is that the examples don't include any import statements so if you try to do a copy-paste, you spend the next 5 mins fixing import errors and installing disparate packages as many examples for non-trivial components end up importing a number of components from multiple packages.

TabList example:

```javascript
<TabList defaultSelectedIndex={2}>
  <TabPanel title="First Tab">
    <Text>Hello World</Text>
  </TabPanel>
  <TabPanel title="Disabled Tab" disabled>
    <Text>{lorem.paragraphs()}</Text>
  </TabPanel>
  <TabPanel title="Third Tab">
    <Text>{lorem.paragraphs()}</Text>
  </TabPanel>
  <TabPanel title="Fourth Tab" maxHeight="10rem">
    <Text>{lorem.paragraphs()}</Text>
  </TabPanel>
</TabList>
```
This has the following dependencies:

1. `Tablist`, `TabPanel` from the `@instructure/ui-tabs` package
2. `Text` from `@instructure/ui-elements`
3. `lorem` from gawd-knows-where

Adding import statements to the examples would be **_hugely_** helpful!

**Comment by arlodesign** [comment]
Imports for InstUI components are shown at the bottom of every page.

<img width="831" alt="TabList Import" src="https://user-images.githubusercontent.com/201878/50707143-8a33dd80-1025-11e9-8643-33c4226c799f.png">

However, some of our imports are not complete. For example, we indicate the import for [`TabList`](https://instructure.design/#TabList) as `import TabList from '@instructure/ui-tabs/es/components/TabList'`, but you must also import `TabPanel`. This import statement should actually be `import TabList, { TabPanel } from '@instructure/ui-tabs/es/components/TabList'`.

We are currently evaluating and prioritizing updates to our documentation in the coming months, and surfacing imports better is on our mind. For that reason, we will leave this issue open to update you on our progress.

`lorem` is the npm package [`lorem-ipsum`](https://www.npmjs.com/package/lorem-ipsum). I'm not sure we would plan to include that, but we understand the confusion. We'll take that into consideration, as well.

Thanks for the feedback!
