### ISSUE TITLE
Find tools to replace the docs client

### ISSUE THREAD

**Issue by HerrTopi** [instructure/instructure-ui#160]
### Context
Docs client

### Summary
We need to pick a tool capable of handling versioning and all currently implemented features of the docs.

### Justification
We'd like to support multiple versions of the project in the docs app. 

### Additional Details
Check out [readthedocs.io ](url), nextjs-MDX, Storybook, (most likely we want to use markdown)

**Comment by matyasf** [comment]
I could not find any out-of-the-box solution for this issue. The closest one is ReadTheDocs:
+ support versions
+ renders `.md` files
- no live code out of the box (I could not find any examples, likely doable with a Sphinx plugin)
- no RTL support, see https://github.com/readthedocs/readthedocs.org/issues/2463
~ Accessibility needs testing

**Comment by matyasf** [comment]
Another contender is [Docusaurus V2](https://v2.docusaurus.io/docs/)
\+ Written in React, is really easy to use React components
\+ maintained by Facebook
\+ supports versions
\+ could not find a way to autogenerate docs from code, we might need to write a plugin for this.
/~ V2 is in alpha (but is already used in lots of places in production)

**Comment by matyasf** [comment]
Open questions:
- Can we reuse our docs from code autogenerator (ui-docs-plugin) in Docusaurus?
- How hard is it to introduce versions to the current tool?

**Comment by matyasf** [comment]
The current `ui-docs-client` would need the following fixes:
- versioning
- emotion migration
- it has many roots in the DOM, this might be a issue
- fix performance issues

We decided to keep the current solution and do the aforementioned fixes.
