### ISSUE TITLE
Error: Cannot find module '.\node_modules\concurrently\bin\concurrently.js/package.json'

### ISSUE THREAD

**Issue by nagaed** [instructure/instructure-ui#175]
### Question
Following the QuickStart instructions to create a new UI app, after:
`yarn`
`yarn start`

I receive the error:
`Error: Cannot find module '.\node_modules\concurrently\bin\concurrently.js/package.json'`

I'm new to frontend building and NPM's package management. 
Is this something to be resolved with the concurrently package?  

And/Or, do I need to install this on an instructure instance to give the libraries 'context'? 

Any advice is gratefully received. thanks.

**Comment by HerrTopi** [comment]
Hey!

I think our "Quick Start Guide" is incomplete.
Please try to follow [https://instructure.design/#contributing](url).

(anyways, I think you are a `yarn bootstrap` away from success :)

**Comment by nagaed** [comment]
Thanks @HerrTopi  for your quick response. OK no problem. I'll use that link.
