### ISSUE TITLE
Form Select component does not trigger dropdown list when clicking on down arrow

### ISSUE THREAD

**Issue by gedion** [instructure/instructure-ui#18]
The select component as documented [here](https://instructure.design/#Select) and as shown below, highlighted in red, does not trigger the dropdown list when clicking on the arrow.

<img width="1402" alt="screen shot 2018-08-09 at 7 58 10 am" src="https://user-images.githubusercontent.com/1224206/43900282-f9f28900-9ba9-11e8-81ab-d5a1d9ddc531.png">

**Comment by personable** [comment]
@gedion Confirmed. Thanks for reporting! I'll open an internal ticket to get it fixed.

**Comment by junyper** [comment]
@gedion Thanks for filing this! This issue was fixed in v5.25.0:

https://github.com/instructure/instructure-ui/commit/3d3bcc1
