### ISSUE TITLE
Pagination component doesn't allow for an aria-label or aria-labeled-by attribute

### ISSUE THREAD

**Issue by dobe0002** [instructure/instructure-ui#20]
When rendered in a browser, the Pagination component inserts a wrapper that either has a role="navigation" attribute or allows you to change the tag to a "nav" tag using the "as" prop.

The issue is that on the rendered pages there maybe more than one navigation landmark.  Multiple landmarks of the same type are confusing especially to screen reader users.  It is best practice  to add an aria-label or aria-labeled-by attribute to let the screen reader user know what that landmark contains.  The "label" prop doesn't solve this issue because when rendered, it isn't programmatically tied to the navigation landmark.

**Comment by arlodesign** [comment]
The `label` prop generates an `aria-labeledby` attribute:

<img width="695" alt="Label prop generating an aria-labeledby attribute in Pagination component" src="https://user-images.githubusercontent.com/201878/50707728-738e8600-1027-11e9-837c-db6d9f771f52.png">

If you don't want the visible label, Pagination will accept an `aria-label` prop:

<img width="686" alt="Pagination component with aria-label prop" src="https://user-images.githubusercontent.com/201878/50707872-ffa0ad80-1027-11e9-8b8e-f84ca0a1d6f0.png">

We would also like to make it so you can pass a `<ScreenReaderContent>`, but there is a cosmetic bug we've identified with that which we now have in our backlog to correct.

All of these examples should be added to our documentation, and we appreciate you point this out to us. 🙇
