### ISSUE TITLE
TreeBrowser component doesn't display full text on hover when child items are truncated.

### ISSUE THREAD

**Issue by shelltr** [instructure/instructure-ui#22]
For the [TreeBrowser](https://instructure.design/#TreeBrowser)

When the TreeButton text gets truncated, there is no way to see the available full text. I think that if a button has been truncated, a ToolTip should be displayed on hover/focus on the element displaying the rest of the text.

<img width="319" alt="Screen Shot 2019-03-20 at 9 57 47 AM" src="https://user-images.githubusercontent.com/5502587/54704270-a3620b80-4af7-11e9-9d4b-44e41b6a31e9.png">

**Comment by arlodesign** [comment]
Thank you for the issue. We're currently discussing different ways we can approach this. We'll keep this issue open so we can update you on the progress.
