### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by alessandrojcm** [instructure/instructure-ui#27]
Hi there!

I see that this library does not have type definitions. For me (and I'm sure that for a lot of developers too), TypeScript is a must and I think that the library could benefit with it. Maybe it's ok if I create those type definitions and add them to [DefinitelyTyped](https://definitelytyped.org/)?

**Comment by alessandrojcm** [comment]
Mmmm... Taking a better look at the project organization, I think it would be better to add the type definitions directly in each package. What do you think?

**Comment by junyper** [comment]
Hi @alessandrojcm . We've added the type definitions in v6.7.0. Thanks for opening the issue!
