### ISSUE TITLE
"[View] 'paddingXSmall' is an invalid 'padding' value" type warnings

### ISSUE THREAD

**Issue by solkimicreb** [instructure/instructure-ui#28]
Hi!

We get a lot of "[View] 'paddingXSmall' is an invalid 'padding' value" type warnings during our test runs and development. Shouldn't [this function](https://github.com/instructure/instructure-ui/blob/2dd401cc63c2bd08b1a073084650a28c66ca8a4f/packages/ui-themeable/src/getShorthandPropValue.js#L42) allow values from [here](https://github.com/instructure/instructure-ui/blob/c295b927a93af75e9233ab3b60945b8848dfc33f/packages/ui-themeable/src/ThemeablePropTypes.js) without a [warning](https://github.com/instructure/instructure-ui/blob/2dd401cc63c2bd08b1a073084650a28c66ca8a4f/packages/ui-themeable/src/getShorthandPropValue.js#L69)?

**Comment by junyper** [comment]
@solkimicreb the allowed values for the padding prop are defined [here](https://github.com/instructure/instructure-ui/blob/master/packages/ui-themeable/src/ThemeablePropValues.js). The documentation should be better for sure, but can you check that you are using `x-small` as the padding value and not `paddingXSmall`?

**Comment by solkimicreb** [comment]
We use `x-small` and it is not just in our package I think. The `paddingXSmall` warning is actually a result of `x-small`. [This line](https://github.com/instructure/instructure-ui/blob/2dd401cc63c2bd08b1a073084650a28c66ca8a4f/packages/ui-themeable/src/getShorthandPropValue.js#L66) is responsible for the x-small -> paddingXSmall transformation. I think the issues is that [this function](https://github.com/instructure/instructure-ui/blob/2dd401cc63c2bd08b1a073084650a28c66ca8a4f/packages/ui-themeable/src/getShorthandPropValue.js#L42) does not accept `x-small` like values.

**Comment by solkimicreb** [comment]
The issue was on our side. I did not import and `.use()` the theme in our unit tests.
Thanks for the help!
