### ISSUE TITLE
Rating component doesn't compile for build correctly

### ISSUE THREAD

**Issue by tylerkowalchuk** [instructure/instructure-ui#333]
### Background Information

**Package Version(s)**:
"@instructure/ui-rating": "7.3.4",

**Browser**:
Safari, Chrome

**OS:**
Mac

**Device:**

**Component**:
Rating

### Describe the Bug
None of the styles for the stars appear in the build compile. The colors, sizes, and other themeable options show up while running the dev version (npm start), but no styles are applied when built for production (npm build).

### Steps To Reproduce
Go to your documentation site and you will see none of the colors or sizes are applied.
https://instructure.design/#Rating

### Expected Behavior
The stars should be blue and different sizes and margins.

### Additional Information

**Current Workaround(s):**
None, other than adding CSS manually.

**Products Affected:**

**Are you willing to submit a PR to fix?**
No, I can't figure out why the different compile options break it.

**Requested Priority:**
Normal

**Comment by matyasf** [comment]
Hi

Thanks for the bug report! We fixed this in our upcoming release (which will happen in 1-2 months), but will look into backporting the fix to InstUI v7 next week

**Comment by matyasf** [comment]
Fixed in 8.0.0
