### ISSUE TITLE
Upgrade immer to version 8.0.1 or later.

### ISSUE THREAD

**Issue by rlorenzo** [instructure/instructure-ui#409]
### Background Information

**Package Version(s)**:
@instructure/ui-webpack-config@7.4.0

### Describe the Bug
We have a Dependabot alert about using a vulnerable version of immer.

>  Dependabot cannot update immer to a non-vulnerable version
The latest possible version that can be installed is 1.10.0 because of the following conflicting dependency:
> @instructure/ui-webpack-config@7.4.0 requires immer@1.10.0 via a transitive dependency on react-dev-utils@9.1.0
The earliest fixed version is 8.0.1.

Need to upgrade the react-dev-utils being used to 11.0.3, which includes this patch that upgrades immer.

https://github.com/facebook/create-react-app/commit/6947896b00a6d8e08b66870299b03360c5fde598#diff-5fa747ee59928aa870b421193b0ad74be1701fe65cfddd1691284dbeac6caa8b

**Are you willing to submit a PR to fix?**
- [ ] Yes, I'm willing to submit a PR

**Requested Priority:**
Blocking

**Comment by matyasf** [comment]
Hi
Thanks for the report, we will look into it

**Comment by matyasf** [comment]
We have released v7.4.3 that fixed this issue
