### ISSUE TITLE
root items not rendered within tree browser when `showRootCollection` is false

### ISSUE THREAD

**Issue by prenner** [instructure/instructure-ui#429]
### Background Information

**Package Version(s)**:
tree-browser v7.4.3

**Browser**:
All browsers

**OS:**
N/A

**Device:**
N/A

**Component**:
TreeBrowser

### Describe the Bug
when `showRootCollection` is false as a `TreeBrowser` prop, items within the root collection are not rendered. Collections belonging to the root collection are rendered correctly, but items are not. 

### Steps To Reproduce
See codepen: https://codepen.io/prenner/pen/wvoRmMY?editors=001

### Expected Behavior
Items within the root collection ("Render me!!" in this case) should be rendered as a sibling of collections within the root. 

### Additional Information

**Current Workaround(s):**
Don't use `showRootCollection` as false. However, there's still not a way to render items at the root level.

**Products Affected:**
Current designs for the Outcomes team, not a live product

**Are you willing to submit a PR to fix?**
- [X] Yes, I'm willing to submit a PR

**Requested Priority:**
Normal

**Comment by ke1k0** [comment]
This fix is released in [v8.1.0](https://instructure.design/#TreeBrowser), and backported in [v7.5.1](https://legacy.instructure.design/#TreeBrowser). 

You can try out here: https://instructure.design/#TreeBrowser/#showrootcollection
