### ISSUE TITLE
feat(ui-tree-browser) make dash at root level customizable

### ISSUE THREAD

**Issue by prenner** [instructure/instructure-ui#457]
### Context
ui-tree-browser (latest)

### Summary
We'd like the display of the dash at the root level to be customizable via props (similar to "showRootCollection") . Specifically, we'd like to customize whether or not the dash is displayed. If there are many root collections or items, this customization should apply to each.
![Screen Shot 2021-03-30 at 11 40 43 AM](https://user-images.githubusercontent.com/5800476/113024972-00fcaa00-914d-11eb-87ff-46c0311bbf48.png)

### Justification

We'd like to hide the dash so we can be in sync with requested designs. It shouldn't change any existing implementations as it's an additional prop.

**Comment by ke1k0** [comment]
Hi @prenner! 
Yesterday I discussed this issue on our weekly meeting with the Design team, and they said that it is fine to have that dash at the root icon, and making it customisable has no additional value in the design system. Making this a settable property on the Component seems like an unnecessary overhead and complexity in the code. Can you please double check with the Designer of this feature?

**Comment by prenner** [comment]
Could we just remove the line altogether (instead of making it customizable)?

**Comment by ke1k0** [comment]
This fix is released in [v8.2.0](https://instructure.design/#TreeBrowser), and backported in [v7.6.0](https://legacy.instructure.design/#TreeBrowser).
