### ISSUE TITLE
bug(ui-tree-browser) remove line that extends into root collection icon

### ISSUE THREAD

**Issue by prenner** [instructure/instructure-ui#458]
### Background Information

**Package Version(s)**:
ui-tree-browser@8.0.0 (latest)

**Browser**:
Chrome

**OS:**
Mac OS

**Component**:
Tree Browser

### Describe the Bug
There is a vertical line that extends into the root collection icon when the TreeBrowser size is large

### Steps To Reproduce
1. Go to https://instructure.design/#TreeBrowser
2. View 'Customizing Icons'
3. Note the vertical line extending into the folder icon for "Saved" (see screenshot below)
   

### Expected Behavior
The line should stop before hitting the icon like in small/medium sizes

### Screenshots
![Screen Shot 2021-03-30 at 1 01 27 PM](https://user-images.githubusercontent.com/5800476/113036665-32c83d80-915a-11eb-95db-a5402d5d2325.png)

### Additional Information

**Current Workaround(s):**
Use a smaller size TreeBrowser, but that isn't always feasible

**Products Affected:**
It doesn't look like any teams currently use a large TreeBrowser

**Are you willing to submit a PR to fix?**
- The Outcomes team can, although we aren't currently planning on using a large sized tree

**Requested Priority:**
Low

**Comment by ke1k0** [comment]
This fix is released in [v8.1.0](https://instructure.design/#TreeBrowser), and backported in [v7.5.1](https://legacy.instructure.design/#TreeBrowser). 

(Might not be pixel perfect, but we tried to "improve the look" without having to rewrite the component. If you have further problems considering this issue, please open a new ticket. :) )
