### ISSUE TITLE
feat(ui-tree-browser) Allow for getCollectionProps that mirrors the functionality of getItemProps

### ISSUE THREAD

**Issue by Seacant** [instructure/instructure-ui#472]
### Context

TreeBrowser

### Summary

A new property on the TreeBrowser component called `getCollectionProps` which takes a function in the shape of `(props) => props`.

### Justification

There is already similar functionality for items in the TreeBrowser in the form of `getItemProps`. This relatively simple change will give us a lot more control over the rendering process for collections and is exactly what I need for the functionality I'm working on.

### Additional Details

I have this working in a PR that I'll link below momentarily for feedback.

**Comment by ke1k0** [comment]
Hi! Just wanted to ask: is this a feature you need in v7 as well, or are you using v8 already?

**Comment by ke1k0** [comment]
This feature is published in [v8.2.0](https://instructure.design/#TreeBrowser).
