### ISSUE TITLE
feat(ui-tree-browser) Allow for control over TreeButton rendering for collections and items

### ISSUE THREAD

**Issue by Seacant** [instructure/instructure-ui#474]
### Context

TreeBrowser

### Summary

Allow for the user to control how we render items and collections so that they can better customize the display of the TreeBrowser. 

### Justification

The TreeBrowser is amazing at displaying hierarchical content but is being held back in that it can only display an icon + a string. If we expose to the user a way to hook into the rendering process so they can write JSX representing each node in the tree, they can create much more detailed UI.

### Additional Details

I can see this being implemented in a few way
1. The simple solution
We're actually already really close to allowing this functionality. For example, If you were to do the following 
```js
<TreeCollection
  ...
  getItemProps={
    (props) => {
      ...props,
      name: <Text color='brand'>{props.id}: {props.name}</Text>
    }
  }
/>
```
it would render exactly as you'd expect but you'll end up with a console error complaining about a propType validation error (since TreeBrowser expects name to be a string, not a node). It's a bit on the ugly side since it's not really a name we're passing anymore but it works and supporting it would be as simple as changing the following:
```js
// src/TreeBrowser/TreeButton/index.js
static propTypes = {
  ...,
  name: PropTypes.oneOfType([PropTypes.string, PropTypes.node]),
  ...
}
```

2. The more 'proper' solution
The other path is to add a new prop _somewhere_ that allows for control over how a TreeButton renders. I could see this either being attached to each individual item/collection entry (like renderAfterNode is) or passed as a new prop to TreeBrowser (ie, `renderItemNode`, `renderCollectionNode`) and called on each item. 

Then, the only question is we actually call that function and inject the results. I could see the argument for wanting to preserve the current DOM as much as possible and thus only allowing injection where we currently have `{name}` below. This would preclude the ability to customize the rendering of both the icon or the descriptor property but given the amount of control we're granting them with this, I don't see that being an issue.

```js
// src/TreeBrowser/TreeButton/index.js
render() {
...
// old
            <span css={styles.textName}>{name}</span>
// new
            <span css={styles.textName}>{renderNode(this.props)}</span>
...
}
```
---
If we can come to agreement on which solution y'all prefer (even if it's dramatically different than what I've proposed), I'd be happy to write a PR implementing it. I can also dive deeper into my use case if you need more justification as to why I need this functionality.

**Comment by ke1k0** [comment]
Thank you for posting the issue! 

As you mentioned, this change would give the developers the ability to customize TreeBrowser, and apart from the problems with preserving the current DOM structure, it may result in visual changes too. This is a topic we need to discuss with the Design team, since they have a big say about how strictly we want to protect the brand visuals.

I would like to ask for your patience while we discuss the issue. In the meantime, it would be much appreciated if you could provide more use cases and/or designs where this functionality could be useful. Thank you!

**Comment by Seacant** [comment]
If you use the new feature, it would definitely involve visual changes since that's the point of using it. If you keep with the defaults, it would not. I made sure that both solutions I proposed would not affect any existing implementations of the TreeBrowser. As you say, it is ultimately up to our designers as to whether such customization is necessary but I'm hopeful that they'll be won over by the beauty of what you can do with it :)

As for use cases in addition to what I shared with you privately, it's really anything. Changing the text color of the nodes, changing sizes, embedding icons/images, allowing for wrapping instead of truncation, and whatever other functionality the user can think of. With such power comes responsibility in how they use it, but users who need this much control are going to find a way to get it regardless so (in my mind) we might as well give them a clean way to do so.

**Comment by matyasf** [comment]
hi!
We have made a PR for this feature - you can customize now the content for the whole item inside a TreeButton, will this be OK for you? You can check it out here: https://github.com/instructure/instructure-ui/pull/493 (just checkout this branch and run `yarn dev`, it has an example under `TreeBrowser`

**Comment by Seacant** [comment]
This is significantly better than what I had proposed! It's exactly what I need. 

Thanks for having such a quick turn around on this. I look forward to seeing it merged.
