### ISSUE TITLE
Error creating app ( 8.0.0)

### ISSUE THREAD

**Issue by gxclarke** [instructure/instructure-ui#478]
### Background Information

**Package Version(s)**:
8.0.0

**Browser**:
N/A

**OS:**
Windows 10

**Device:**
PC

**Component**:
N/A

### Describe the Bug
Error installing

### Steps To Reproduce

    Steps to reproduce the behavior, e.g.:
    1. Install latest LTS of node and latest npm
    2. npx @instructure/instui-cli create app --name MyInstuiApp
    3. See error: Encountered an error generating source from the template:  ReferenceError: componentTheme is not defined

### Expected Behavior
Install completes without error

### Additional Information

**Current Workaround(s):**

**Products Affected:**

**Are you willing to submit a PR to fix?**
- [ ] Yes, I'm willing to submit a PR

**Requested Priority:**

**Comment by matyasf** [comment]
Thanks for the report we are looking into it

**Comment by matyasf** [comment]
Fixed by https://github.com/instructure/instructure-ui/pull/479

**Comment by matyasf** [comment]
Fixed in 8.1.0
