### ISSUE TITLE
Extract themeing code into a separate repo

### ISSUE THREAD

**Issue by mvf4z7** [instructure/instructure-ui#5]
I was curious if you guys ever thought about extracting your themeing code to a separate general purpose package. I really like your approach to themeing and would love to bring it into my own project.

**Comment by junyper** [comment]
@mvf4z7 Yes--In fact I'm working on that now! Hopefully we'll have it extracted sometime in early January. I'd love to see it used in other projects.

**Comment by mvf4z7** [comment]
That sounds great! Does your theming support server side rendering? I was checking out the Instructure UI component library webpage that has examples of all the components. When I opened the browser dev tools I noticed that the styles are all injected via inline style blocks. Another theming library I was trying to use took a similar approach with inline style blocks and I would get a flash of unstyled content whenever server side rendering was enabled.

**Comment by junyper** [comment]
@mvf4z7 In theory it should support server side rendering of the CSS but I haven't tested it out yet.

**Comment by Geeman201** [comment]
Hey @junyper 

I'm hoping to use this component library in a few weeks (I love how accessible it is), did you complete theming? if not, what's left, I'd be more than happy to help finish it off.

James

**Comment by junyper** [comment]
Hi @Geeman201. We have a small API change coming for applying themes in v2.0.0 which I hope to release this week. We're also planning to add a lot of documentation around the theming as soon as we can. Thanks!

**Comment by Geeman201** [comment]
@junyper Cool ok, 

I'll wait until you get v2.0.0 out prior to having a play and will let you know how it goes!

**Comment by mvf4z7** [comment]
Any update on this issue?

**Comment by junyper** [comment]
2.0.0 will hopefully go out today or Monday. If not, I'll release a beta version.

**Comment by junyper** [comment]
v2.0.0 is out on npm now with the updates to themeable. We haven't extracted it yet, but we're working on extracting both it and the documentation generation code. There will be lots of documentation updates in v2.1.0

**Comment by Geeman201** [comment]
@junyper Great thanks! Looks great! I suggest this issue is closed and if necessary a new one opened to continue the discussion. 

James
