### ISSUE TITLE
Unnecessary space rendered for Select component

### ISSUE THREAD

**Issue by tamasjakli** [instructure/instructure-ui#500]
### Background Information

**Package Version(s)**:
ui-select 8.1.0

**Browser**:
Chrome, Safari

**OS:**
macOS

**Device:**
MacBook Pro

**Component**:
Select

### Describe the Bug
There's a prop renderBeforeInput (I believe renderAfterInput has the same problem) which accepts either a node or a function.
I passed down a function which returned null, but nevertheless an unnecessary space for an icon was rendered.

### Steps To Reproduce
Second Select component has a function returning null as the value for renderBeforeInput.
https://codepen.io/tamasjakli/pen/NWdEoQx?editors=001

### Expected Behavior
No space should be rendered for the icon if function returns null.

### Screenshots
<img width="633" alt="Screen Shot 2020-09-30 at 21 35 15" src="https://user-images.githubusercontent.com/24220801/115706341-d1b51380-a36d-11eb-8c50-8eb07516d132.png">

### Additional Information

**Current Workaround(s):**
Instead of passing down the function as a prop, just pass whatever the function returns.

**Products Affected:**

**Are you willing to submit a PR to fix?**
- [ ] Yes, I'm willing to submit a PR

**Requested Priority:**
Low

**Comment by ke1k0** [comment]
This bug is fixed in [version 8.2.1.](https://instructure.design/#CHANGELOG). Thank you for posting the issue!

**Comment by ke1k0** [comment]
More info in the [PR](https://github.com/instructure/instructure-ui/pull/505), if you are interested: this bug affected TextInput, Select and SimpleSelect.
