### ISSUE TITLE
[Security] Potential Secret Leak

### ISSUE THREAD

**Issue by raima-zachariah** [instructure/instructure-ui#515]
It has been noticed that while using chromaui/action@v1 your projectToken d8b52d7c3367 is present in plaintext. Please ensure that secrets are encrypted or not passed as plain text in github workflows.

**Comment by Brailor** [comment]
Hi!
Thanks for the report!
This is done on purpose so the GitHub Chromatic action can be run on forked repository PRs.
It is the recommended way of enabling forked PRs for open source projects. You can read more about it [here](https://www.chromatic.com/docs/github-actions).

**Comment by raima-zachariah** [comment]
Thank you for the response! I was analysing a vulnerability and this came out in the results. Please feel free to close the issue.
