### ISSUE TITLE
Theme overrides example provided in docs doesn't work

### ISSUE THREAD

**Issue by fbegue** [instructure/instructure-ui#612]
I've upgraded everything to v8 and am trying to migrate my local component theme overrides from 'ApplyTheme' (now deprecated) to 'EmotionThemeProvider'. But the *only* example you guys provide for this under 'Theme overrides [here](https://instructure.design/#EmotionThemeProvider) doesn't work in my application or in the Codepen linked under it. 

Similar case with the 'Global component theme overrides' example - although it looks like *some* things are working there - like this  [List.Item.componentId] override which is completely foreign to me.

Any help would be appreciated

**Comment by matyasf** [comment]
hi!

The example in Codepen does not work because by default we're including some imports in our site and not in codepen causing the faul (thanks for the report, we'll fix it) Here is a working example in Codepen, likely you are missing to import the themes:

```
// import this in your code just from @instructure/ui-themes and add this as a dependency to you package.json
import { canvas } from "https://cdn.skypack.dev/@instructure/ui-themes"

const render = (el) => { ReactDOM.render(el, document.getElementById('app')) }

render(<div>
   <EmotionThemeProvider theme={canvas}>

  <Alert variant="info" margin="small">
    I am a default style Alert.
  </Alert>

  <EmotionThemeProvider
    theme={{
      themeOverrides: {
        canvas: {
          colors: { backgroundLightest: 'orange' }
        },
        'canvas-high-contrast': {
          colors: { backgroundLightest: 'red' }
        },
        instructure: {
          colors: { backgroundLightest: 'green' }
        }
      }
    }}
  >
    <Alert variant="info" margin="small">
      My background should be:
      <List margin="xx-small">
        <List.Item><strong>orange</strong> in 'canvas',</List.Item>
        <List.Item><strong>red</strong> in 'canvas-high-contrast',</List.Item>
        <List.Item>and <strong>green</strong> in 'instructure' theme.</List.Item>
      </List>
    </Alert>
  </EmotionThemeProvider>
  </EmotionThemeProvider>
</div>)
```

**Comment by matyasf** [comment]
I'll close this issue due to inactivity, if you have any other concerns you can just reply here.
