### ISSUE TITLE
Screen Readers and Browsers

### ISSUE THREAD

**Issue by brichwin** [instructure/instructure-ui#660]
### Question
Is the accessibility support for Instructure UI and JAWS still Firefox only?

On the [Canvas Accessibility Standards page](https://community.canvaslms.com/t5/Canvas-Basics-Guide/What-are-the-Canvas-accessibility-standards/ta-p/1564) it says that on Windows these combos are supported:
- JAWS (latest version for Chrome/Firefox on Windows)
- NVDA (latest version for Chrome/Firefox on Windows)
 
However, on the [Instructure UI page](https://instructure.design/#index) is says:

> Leading screen readers: VoiceOver, NVDA, and JAWS (Firefox only)

### Additional Details
We would love to have our local developers that are extending Canvas at Indiana University use the Instructure UI instead of their own design system. We think that would help non-visual users especially if the controls are all consistent. However, most of our students that use JAWS use Chrome as their web browser.

I was wondering if since Canvas now supports Firefox and Chrome browsers with JAWS, then does that mean that support for the Chrome browser and JAWS has been addressed in Instructure UI now as well?

**Comment by HerrTopi** [comment]
Thanks for the question, this is a good one! I have to look into it and I'll get back to you ASAP

**Comment by HerrTopi** [comment]
Thanks for the wait: I consulted with our a11y team and confirmed, that although canvas went through with an a11y audit with JAWS and chrome, InstUI did not. Regardless of that, canvas uses most of InstUI's components, so it should work as intended.
Just to be sure, I've requested an audit for InstUI as well. It will take a couple of days, maybe 1-2 weeks and I'll come back to you with the results!

Best regards

**Comment by brichwin** [comment]
Wow, no wait at all! Thanks for the info and I am curious to hear about the results. 1-2 weeks is fine on our end - I've done many such reviews and I know the effort required!

**Comment by HerrTopi** [comment]
Hey, thanks for the wait!

I've got news from our audit team so let me update you: according to their estimate, the audit will be done sometime late next week. I'll get back to you as soon as it happens.

**Comment by HerrTopi** [comment]
Hello,

once again: thanks for the wait! It took a bit longer than expected, but the audit been concluded. 
The result is: we support Chrome as well so feel free to use it.

Thanks againg for contacting us with this issue
