### ISSUE TITLE
Iframe Same-origin policy blocking instucrure-ui

### ISSUE THREAD

**Issue by raman-savitski-instructure** [instructure/instructure-ui#718]
### Background Information

**Package Version(s)**: ui-dom-utils v.8.7.0

**Browser**: Chrome (All Versions)

**OS:** Windows 10 Pro

**Component**: getFrameDocumentSafe

### Describe the Bug
Iframe Same-origin policy blocking instucrure-ui if any IFRAME is not same-origin, i.e. it can't be accessed. As result an error is thrown.

instructure-ui components like "Popover", "Modal", etc... are trying to set document "mouseup" event listeners inside every iframe on the page.
This is performed by using `FocusRegion.activate`.
```
        Array.from(doc.getElementsByTagName('iframe')).forEach((el) => {
          // listen for mouseup events on any iframes in the document
          const frameDoc = getFrameDocumentSafe(el)
          .......
```
The problem is inside `getFrameDocumentSafe`
```
function getFrameDocumentSafe(el: HTMLIFrameElement) {
  return el.contentDocument || el.contentWindow?.document || null
}
```
If trying to access `el.contentWindow?.document` of iframe - JS error will be thrown "Uncaught DOMException: Blocked a frame with origin "...." from accessing a cross-origin frame".

I don't think `el.contentWindow?.document` is required here.
According to [mozilla](https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/contentDocument) `el.contentDocument` is supported by all browsers and should be enough.

### Steps To Reproduce
Codepen example: just open browser console and click "TEST" button.
https://codepen.io/raman-savitski-instructure/pen/eYRVVGZ?editors=1000

**Requested Priority:** Blocking

**Comment by matyasf** [comment]
Thanks for the detailed report, we will fix it ASAP

**Comment by matyasf** [comment]
Fixed with https://github.com/instructure/instructure-ui/pull/720 , this will go out with the next release.

**Comment by raman-savitski-instructure** [comment]
@matyasf Thanks a lot for quick fix. Any ETA on next release date?

**Comment by raman-savitski-instructure** [comment]
> I'm closing the ticket, but let us know if you have further problems!

Working as expected. No errors now. Thank you.
