### ISSUE TITLE
`width="fit-content"` for <View /> not working in Firefox 

### ISSUE THREAD

**Issue by gromaco** [instructure/instructure-ui#729]
### Background Information

**Package Version(s)**:
ui-view v8.8.0 
**Browser**:

**Component**:
View

### Describe the Bug
`<View width="fit-content" /> `
`fit-content` doesn't work in Firefox.
It's not prefixed with `-moz-`
 
### Steps To Reproduce

   1. Go to [https://codepen.io/gromaco/pen/BaZeqKZ?editors=001](https://codepen.io/gromaco/pen/BaZeqKZ?editors=001)
   2. Check it in Chrome
   3. Check it in Firefox

### Expected Behavior
`-moz-fix-content` is set for `View`

### Additional Information

Currently, width(and a lot of other props) is set as inline style

https://github.com/instructure/instructure-ui/blob/d3ef347fa5e8b3126659528defa4a6e4408bf01e/packages/ui-view/src/View/index.tsx#L222

https://github.com/instructure/instructure-ui/blob/d3ef347fa5e8b3126659528defa4a6e4408bf01e/packages/ui-view/src/View/styles.ts#L602
```
inlineStyles: {
      ...spacingStyle,
      ...borderStyle,
      ...offsetStyle,
      width,
      height,
      minWidth,
      minHeight,
      maxWidth,
      maxHeight,
      ...getStyleProps(props)
    }

```
So it's not processed by `Stylis` (https://github.com/thysultan/stylis.js) unlike styles applied by Emotion `css` prop.

**Are you willing to submit a PR to fix?**
- [ ] Yes, if needed, but not sure at the moment what solution should be applied

**Requested Priority:**
High

**Comment by Brailor** [comment]
Hi!
Thank you for the detailed bug report.
We will look into it and get back to you.
