### ISSUE TITLE
Can't resolve '@babel/runtime/helpers/esm/objectSpread2'

### ISSUE THREAD

**Issue by buckett** [instructure/instructure-ui#73]
When upgrading from 6.10 to 6.12 I got the following error when attempting to compile:
```
Failed to compile.

./node_modules/@instructure/canvas-theme/es/index.js
Module not found: Can't resolve '@babel/runtime/helpers/esm/objectSpread2' in '.../node_modules/@instructure/canvas-theme/es'
```

Reverting back to 6.10 fixes this. With both 6.10 and 6.12 looking in my `package-lock.json` I see the same babel runtime dependency:
```
    "@babel/runtime": {
      "version": "7.4.3",
      "resolved": "https://registry.npmjs.org/@babel/runtime/-/runtime-7.4.3.tgz",
      "integrity": "sha512-9lsJwJLxDh/T3Q3SZszfWOTkk3pHbkmH+3KY+zwIDmsNlxsumuhS2TH3NIpktU4kNvfzy+k3eLT7aTJSPTo0OA==",
      "requires": {
        "regenerator-runtime": "^0.13.2"
      }
    },
```
Forcing babel to a newer version in my project allowed me to continue using 6.12 without the error:
```
    "@babel/runtime": "^7.6.0",
```

**Comment by buckett** [comment]
There are mentions of objectSpread2 from 7.5.1 in the babel changelog: https://github.com/babel/babel/blob/master/CHANGELOG.md

**Comment by junyper** [comment]
Thanks @buckett! I'll push up a commit that will require at least 7.5 of babel/runtime and we'll run a patch release with that.
