### ISSUE TITLE
<Pill> doesn't re-render children when they change (<TruncateText>)

### ISSUE THREAD

**Issue by buckett** [instructure/instructure-ui#74]
I am using a `<Pill>` to display a status for an item on the page and have a method that returns one of two pills depending on the status. My code works fine when component gets re-mounted between renders but if the props passed to it are updated then the Pill changes colour but doesn't update it's text.

This is a Storybook story that shows the issue:
```
export const changeState = () => React.createElement(() => {
  const [good, setGood] = React.useState(true);
  return (
    <div>
      <Button margin="small" onClick={() => setGood(prev => !prev)}>Switch</Button>
      { good ?
        <Pill color="success">Good</Pill> :
        <Pill color="danger">Bad</Pill>
      }
    </div>
  );
});
```
When you click the button the colour of the pill changes, but the text never switches between good/bad.This looks to be a bug actually in `<TruncateText>` which is used by `<Pill>`

**Comment by buckett** [comment]
My workaround for this is to just set a key on each of the `<Pill>` and this way React just replaces the element when it changes and it bypasses the bug in TruncateText.

**Comment by kmeleta** [comment]
Thanks @buckett, we've reproduced this issue on our end and will be looking into it.

**Comment by buckett** [comment]
@HerrTopi Is this one fixed in a newer release?

**Comment by HerrTopi** [comment]
@buckett We are working on a new version of TruncateText and the overhaul of the theming solution as well, please use your workaround in the time being.
