### ISSUE TITLE
<TruncateText> is VERY slow with large amounts of content.

### ISSUE THREAD

**Issue by buckett** [instructure/instructure-ui#79]
If you pass a reasonable amount of content to `<TruncateText>` then it stalls the brower for seconds while it does it's thing. Passing 8k of text to it:
```
export const long = () => (<TruncateText>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac tortor dignissim convallis aenean et tortor at. Felis bibendum ut tristique et. Vulputate sapien nec sagittis aliquam malesuada. Neque gravida in fermentum et sollicitudin. Vestibulum sed arcu non odio euismod. Ac turpis egestas sed tempus urna. Porttitor lacus luctus accumsan tortor posuere ac ut consequat semper. Aliquam id diam maecenas ultricies mi eget mauris pharetra et. Turpis cursus in hac habitasse. Dolor purus non enim praesent elementum facilisis leo vel. Nisi lacus sed viverra tellus in hac habitasse. Faucibus vitae aliquet nec ullamcorper sit amet. Rutrum quisque non tellus orci ac auctor augue mauris augue. Et tortor at risus viverra adipiscing at in tellus integer. Est placerat in egestas erat. Morbi leo urna molestie at elementum eu facilisis. Nisl suscipit adipiscing bibendum est ultricies. Leo in vitae turpis massa sed elementum tempus egestas sed.

[...snipped to save space...]

</TruncateText>);
```

Takes multiple seconds on a new laptop.

**Comment by pamhiett** [comment]
@buckett Thank you so much for the submission. We have filed a ticket on our end with a lower priority as the component was never intended to be used with that amount of text.

**Comment by buckett** [comment]
@pamhiett Sure thanks, I suspected as much. What is the expected size this component will cope with and could we just add a small note to the documentation to say this?

**Comment by pamhiett** [comment]
@buckett Splendid idea... I had actually added a note to the ticket to add documentation around text limits. As far as limits, we expected consumers to use this component for an average-sized paragraph at the most, otherwise performance will start to suffer.
