### ISSUE TITLE
Default theme usage doesn't work in a react-script "optimized production build"

### ISSUE THREAD

**Issue by monbrey** [instructure/instructure-ui#81]
The standard method of `import '@instructure/canvas-theme'` works perfectly in the development environment, spun up by `react-scripts start`.

However when running `react-scripts build` for an "optimized production build" and running/serving that, the site does not display any Canvas theming, eg Times New Roman fonts etc.

To resolve this, I had to import and use the `theme` variable, even without making any changes:
```js
import { theme } from '@instructure/canvas-theme'
theme.use()
```

I'm guessing this was to prevent tree-shaking / something TypeScript saw as an unused import.

**Comment by serikjensen** [comment]
@Monbrey thank you so much for bringing this up, it's a good find. We're considering a lot of things about the developer UX with theming. I think ideally we'd just take care of this boilerplate altogether for the consumer in the future if all they want is the default canvas-theme.

In any case, we should probs enforce the .use() syntax moving forward to avoid this. We'll have to keep the existing syntax around to avoid a breaking change until another major version, but maybe we can throw a warning explaining this as a possibility in the meantime. We'll create an issue on our end and keep you posted. Thanks again!
