### ISSUE TITLE
TextArea doesn't remember scroll position

### ISSUE THREAD

**Issue by buckett** [instructure/instructure-ui#810]
### Background Information

**Package Version(s)**:
ui-text-area  8.12.0

**Browser**:
Chrome

**OS:**
Mac OS

**Component**:
`<TextArea>`

### Describe the Bug

If you have a TextArea component that has a `maxHeight` set as outlined in https://instructure.design/#TextArea then if you have a `maxHeight` property then when editing content near the start of the textarea it always scrolls to the end.

### Steps To Reproduce
    Steps to reproduce the behavior, e.g.:
    1. Create a `<TextArea>` with a `maxHeight`, this can be seen on https://instructure.design/#TextArea
    2. Paste in some content so that there is a scroll bar in the component, any text will do.
    3. Scroll up to the first line of text and attempt to edit the text.
    4. The component will scroll to show the last line and so you can no longer see the text you are editing.

### Expected Behavior

The component should show the cursor instead of scrolling to the end.

### Screenshots

This shows appending to the last line is fine, but when I try to type on the first line is scrolls to the last line, hiding the cursor.

https://user-images.githubusercontent.com/5921/142864259-695027aa-6a68-452b-a79a-5854add43df1.mov

### Additional Information

**Current Workaround(s):**

Don't use `maxHeight` property.

**Are you willing to submit a PR to fix?**
- [ ] Yes, I'm willing to submit a PR

**Requested Priority:**

**Comment by HerrTopi** [comment]
Thanks for the report! We are looking into this and will let you know whet it's fixed

**Comment by matyasf** [comment]
@buckett We have released a bix for this in InstUI 8.13.0, did this solve you issue? https://github.com/instructure/instructure-ui/releases/tag/v8.13.0
