### ISSUE TITLE
Types of Table not working properly?

### ISSUE THREAD

**Issue by dferber90** [instructure/instructure-ui#82]
First of all, thanks for this extremely useful component library. I use it to build a small SaaS-app and it's been a perfect fit so far.

I recently started to convert my project to TypeScript and noticed that there are some problems with `Table`.

```tsx
import { Table } from "@instructure/ui-table";

export default function Example() {
  return (
    <Table caption="hello">
      <Table.Head>
        <Table.Row>
          <Table.ColHeader id="cal-from" width="5rem">
            From
          </Table.ColHeader>
          <Table.ColHeader id="cal-until" width="5rem">
            Until
          </Table.ColHeader>
          <Table.ColHeader id="cal-title">Title</Table.ColHeader>
        </Table.Row>
      </Table.Head>
      <Table.Body>
        {appointments.map((appointment, appointmentIndex) => (
          <Table.Row key={appointmentIndex}>
            <Table.Cell>
              {appointment.start}
            </Table.Cell>
            <Table.Cell>
              {appointment.end}
            </Table.Cell>
            <Table.Cell>{appointment.label}</Table.Cell>
          </Table.Row>
        ))}
      </Table.Body>
    </Table>
  );
}
```

The problem I'm seeing is that

```
Property 'Head' does not exist on type 'typeof Table'.  TS2339

    158 |                         caption="hello"
    159 |                       >
  > 160 |                         <Table.Head>
        |                                ^
    161 |                           <Table.Row>
    162 |                             <Table.ColHeader id="cal-from" width="5rem">
    163 |                               From
```

This error pops up when I'm trying to use  `Table.Head`, `Table.Row`, `Table.ColHeader`, `Table.Body`, or `Table.Cell`.

I would have expected this to "just work". Am I doing something wrong or is this a problem in the types?

**Comment by serikjensen** [comment]
Hello @dferber90! Thank you so much for reaching out, I'm glad you've found our lib helpful.

Our typescript support is not great at the moment. Type declaration files are autogenerated and published with the build kind of as an afterthought. That works ok for simple top level components, but falls apart for child components (as you've discovered here).

We're looking to get the bandwidth to level up our type support but we have other commitments right now that will probably keep us busy through Q1. We would definitely be open to a PR though if someone can tackle these issues sooner.

The type generation is currently happening here https://github.com/instructure/instructure-ui/blob/master/packages/ui-scripts/lib/generate-types.js As can be seen, globby is only pulling in the top level index file (not nested dirs) so exploring that would be a good place to start.

Thanks again for reaching out!

**Comment by dferber90** [comment]
I'll close this as it seems like you're aware of the TypeScript issues and this issue is too specific. Thanks for your detailed response!

For anybody else stumbling upon this issue, I used the following workaround:

```typescript
// instructure__ui-table.d.ts

// augment types of Table as they currently seem broken inside @instructure
// see: https://github.com/instructure/instructure-ui/issues/82

declare module "@instructure/ui-table" {
  import {
    Component,
    ComponentType,
    MouseEventHandler,
    ReactNode
  } from "react";
  import "@instructure/ui-table";

  class Table extends Component<{
    caption: ReactNode;
    layout?: "auto" | "fixed" | "stack";
    hover?: boolean;
    margin?: string;
  }> {
    public static Body: ComponentType<{
      hover?: boolean;
      isStacked?: boolean;
      headers?: unknown[];
    }>;
    public static Cell: ComponentType<{
      isStacked?: boolean;
      header?: ReactNode;
      textAlign?: "start" | "center" | "end";
    }>;
    public static ColHeader: ComponentType<{
      id: string;
      width?: string | number;
      textAlign?: "start" | "center" | "end";
      sortDirection?: "none" | "ascending" | "descending";
      onRequestSort?: (event: MouseEvent, { id: string }) => void;
    }>;
    public static Head: ComponentType<{
      isStacked?: boolean;
    }>;
    public static Row: ComponentType<{
      hover?: boolean;
      isStacked?: boolean;
      onClick?: MouseEventHandler;
      headers?: ReactNode;
    }>;
    public static RowHeader: ComponentType<{
      isStacked?: boolean;
      textAlign?: "start" | "center" | "end";
      onClick?: MouseEventHandler;
    }>;
  }
}
```

This extends/overwrites the types provided from `@instructure/ui-table`. I'm not super familiar with how to properly write these definition files, but this was good enough to silence the error messages and can be expanded.
