### ISSUE TITLE
add Date Range Input

### ISSUE THREAD

**Issue by MatheusRV** [instructure/instructure-ui#86]
How could I help implement this? Where to start?

**Comment by kmeleta** [comment]
We don’t have firm direction on a date range type component from our internal design team right now. Without a specific need for the pattern we can’t commit to creating or supporting such a component, especially one with potentially complex UX considerations.

However, if you’d like to implement a date range component in your own app using InstUI I’d recommend looking at ui-calendar, ui-selectable, and ui-date-input for ideas on how you can achieve that.
