### ISSUE TITLE
Support target prop on <Link>

### ISSUE THREAD

**Issue by buckett** [instructure/instructure-ui#88]
Would you consider adding support for the target attribute to the <Link> element?

**Comment by kmeleta** [comment]
Even if we don't explicitly document them, we do usually allow valid dom attributes to be passed through to the underlying dom node in our components. Link should already allow a target prop. If you're seeing otherwise, let us know and we'll investigate.

**Comment by buckett** [comment]
Ah yeah, by bad, it's getting passed through fine. Apologies for the noise.
