### ISSUE TITLE
DateInput needs name attribute for React-Hook-Form integration

### ISSUE THREAD

**Issue by craig-o-curtis** [instructure/instructure-ui#89]
The `DateInput` does have an `inputRef` attribute, which is great.
But for React-Hook-Form to work, it needs a `name` attribute passed in.

The current error in the console
<img width="535" alt="Screen Shot 2020-03-08 at 1 14 10 PM" src="https://user-images.githubusercontent.com/12050799/76170391-c0e01900-613e-11ea-8b1a-a49a6f1f3315.png">

This just needs to be an optional parameter to the `DateInput` @instructure/ui-date-input component for those needed the name attribute on the inner input element.

This name attribute does work when passed in to the `Select` @instructure/ui-select. So the same solution should work.

![Screen Shot 2020-03-08 at 1 16 01 PM](https://user-images.githubusercontent.com/12050799/76170438-2502dd00-613f-11ea-94db-4c8b0c125618.png)

The `TextInput` being rendered inside the `DateInput` component does work when accepting a `name` attribute.

**Comment by kmeleta** [comment]
@craig-o-curtis you are correct. Currently DateInput is not passing through valid dom attributes (like name) to the underlying input. We've opened an internal ticket and should have a fix for this out with the next minor release. Thanks!
