### ISSUE TITLE
Resolving duplicate theme errors

### ISSUE THREAD

**Issue by buckett** [instructure/instructure-ui#90]
While working on a project I started getting lots of warning in the console about duplicate themes:

    Warning: [themeable] A theme registry has already been initialized. Ensure that you are importing only one copy of '@instructure/ui-themeable'. 

my first attempt at resolving this was to make sure that all my dependencies were of the same release, I'd accidentally ended up with some from 6.21 and some from 6.22. However after resolving these inconsistencies I was still seeing these errors in the console. When looking at the output of `npm ls` lots of the `@instructure/ui-themeable@6.22.0` weren't listed as deduped. The fix for this was to run `npm dedupe` and now I am warning free.

Creating this issue partly for Google (when I forget in 3 months time) and partly as I was wondering if the error message could be more helpful in pointing at what problem might be?

**Comment by personable** [comment]
Thanks for bringing this up, Matthew. I'll make an internal ticket to look at the error message and see if we can improve it. Incidentally, if you'd ever want to have a quick call with us to talk about Instructure UI, we'd love to chat. We're just interested in seeing how developers beyond Instructure are using the library, and whether or not their experience has been a good one. No pressure if you're busy. Thanks!
