### ISSUE TITLE
Instructure UI can be slow with lots of components

### ISSUE THREAD

**Issue by buckett** [instructure/instructure-ui#91]
I've got a small renderer of sub-accounts and when trying to display 100 sub-accounts I get a pause of ~1 second to render it:
<img width="1401" alt="Screenshot 2020-04-13 at 12 13 46" src="https://user-images.githubusercontent.com/5921/79116393-4713fe80-7d80-11ea-929b-a2335f33756c.png">

Although there's lots of stuff I could probably be doing better if I switch away from Instructure UI to plain HTML (`<List> -> <ul>`, `<Link> -> <a>`, etc) everything becomes 10x faster (taking ~100ms for the same data):
<img width="1167" alt="Screenshot 2020-04-13 at 12 16 52" src="https://user-images.githubusercontent.com/5921/79116582-c99cbe00-7d80-11ea-92d1-301452c91323.png">

While I understand Instructure UI is always going to be slower than raw HTML elements as it's got more processing todo this gap seems to be rather large.

**Comment by buckett** [comment]
I found 3d4ea2565ff5279208d3e9925c02fa3272e2717c and it looks like this be one step on the path to improving performance.

**Comment by serikjensen** [comment]
Hey @buckett! Know that that commit should only impact test performance as that warning was already getting removed from the production bundle by a macro.

Yes the primary culprit for these performance hits is themeable. We are looking into reevaluating the existing approach and possibly leveraging third party tools to help. We'll keep you posted!

**Comment by buckett** [comment]
@serikjensen Ok, thanks. I was seeing performance problems in development mode, so hoped it might improve things, but in testing it doesn't seem to make much of a difference locally even when I use the updated View.

Not looking for a commitment, but do you have an idea about how soon you might be addressing the performance impact of themeable?
