### ISSUE TITLE
Canvas theme text colours don't pass WCAG AA

### ISSUE THREAD

**Issue by buckett** [instructure/instructure-ui#92]
Some of the colours in the canvas theme don't pass WCAG AA due to being low contrast. They are acceptable at larger font sizes, but not at the default:
<img width="330" alt="Screenshot 2020-05-04 at 10 53 02" src="https://user-images.githubusercontent.com/5921/80955275-eca61500-8df6-11ea-89c6-3c3faa2b9e4f.png">
<img width="336" alt="Screenshot 2020-05-04 at 10 52 51" src="https://user-images.githubusercontent.com/5921/80955280-ef086f00-8df6-11ea-9631-822afeb4e6dc.png">
Not sure what the best "fix" is.

**Comment by dansasaki** [comment]
Hello we have a high contrast theme available and all of the colors in the canvas-high-contrast theme will be over 4.5:1 ratio against white background:  [Instructure-UI High Contrast](https://instructure.design/#canvas-high-contrast)
please let us know if you have any additional questions

**Comment by buckett** [comment]
Magic, thanks and for anyone using Instructure-UI through an LTI you can ask to have the user's high contrast setting passed through on the LTI launch: using the variable `$Canvas.user.prefersHighContrast` which is documented on:
https://canvas.instructure.com/doc/api/file.tools_variable_substitutions.html

**Comment by buckett** [comment]
When I first visited the theme page I didn't see the contract checked (it was below the fold on my browser), but it's really nice, makes checking these things easy:

<img width="945" alt="Screenshot 2020-05-05 at 10 24 28" src="https://user-images.githubusercontent.com/5921/81052066-bb8f1880-8eba-11ea-951f-ff03e92ca848.png">

well done, and thanks.
