### ISSUE TITLE
TreeBrowser sort across both collections and items, rather than within collections then within items

### ISSUE THREAD

**Issue by theotherdy** [instructure/instructure-ui#954]
### Summary
Tree Browser was presumably developed to support the Canvas Files tool and does indeed behave like Windows File Explorer - showing first collections and then items. This closed issue: [Add sort property to TreeBrowser collections](https://github.com/instructure/instructure-ui/issues/752) has added the ability to sort both collections and items (thank you!), but collections are always shown before items. For more general use for browsing hierarchical content, however, the ability to sort across both collections and items would be useful.

### Justification
Imagine browsing a list of fruit and vegetables:

- Apples
-- Cooking
-- Dessert
- Banana
- Cucumber
-- Greenhouse
-- Outdoor

We would definitely like 'Banana' to appear as above, even though it has no sub-collections/items, rather than after 'Cucumber', as will happen with current sort implementation.

**Comment by HerrTopi** [comment]
Hi! Thanks for the report and the nice words.

I am not sure if this is deliberate decision canvas needs or just an oversight. I'll take this to our desing team and ask them. I'll get back to you as soon as I can

**Comment by NamNguyenInstructure** [comment]
Hi, thank you for reporting the problem.

I think your suggestion about separate sorting with collections and items was right. I will discuss this with the other members. For now, I had implement a possible solution in your case [here](https://codesandbox.io/s/tree-browser-demo-xxlz22?file=/src/App.tsx)

**Comment by Brailor** [comment]
Hi! 
Just wanted to inform you that we merged the PR (#1005) that addresses this issue, we will soon make a release which will contain the change.

What we did in the PR:
 -  you can specify a `compareFunc` on your `collections`/`items` which will determine the correct sort order for the TreeBrowser nodes
 - example: https://github.com/instructure/instructure-ui/pull/1005/files#diff-b5f4183d04f4dfe3bbbf0d0033950567b9327e3e25cb8aaaf1e0252a8d7a646dR458-R518

**Comment by theotherdy** [comment]
That

> Hi! Just wanted to inform you that we merged the PR (#1005) that addresses this issue, we will soon make a release which will contain the change.
> 
> What we did in the PR:
> 
> * you can specify a `compareFunc` on your `collections`/`items` which will determine the correct sort order for the TreeBrowser nodes
> * example: https://github.com/instructure/instructure-ui/pull/1005/files#diff-b5f4183d04f4dfe3bbbf0d0033950567b9327e3e25cb8aaaf1e0252a8d7a646dR458-R518

That's brilliant - thank you!

**Comment by buckett** [comment]
I think this is released now in: https://github.com/instructure/instructure-ui/releases/tag/v8.24.3

**Comment by theotherdy** [comment]
Thank you. Not sure whether I’ve misunderstood but that seems to have turned ‘Bananas’ into a collection, and it then appears at the top of the list, not in alphabetical order ie before Apples?
BW
Damion

**Comment by NamNguyenInstructure** [comment]
Hi,
This is an example in case you want to place the empty collection above the others. In the beginning, I misunderstood your desired feature. I thought that you want to sort the collections base on the number of their children.
