### ISSUE TITLE
SimpleSelect not reading options aloud to screen reader users

### ISSUE THREAD

**Issue by atarisafari** [instructure/instructure-ui#974]
### Background Information

**Package Version(s)**:
ui-simple-select": "^8.7.0

**Component**:
SimpleSelect

**Screen Reader:**
JAWS, NVDA

### Describe the Issue
Some of our screen reader users are reporting that when the SimpleSelect component is expanded, the options are not read aloud by the screen reader. Not sure if there's an error in how we are using the component, so any clarification would be appreciated.

### Example Code
`<SimpleSelect
              renderLabel={this.props.t('label.admin.account')}
              value={`${this.props.filters.accountId}`}
              onChange={this.handleAccountSelect}
              isInline={true}
            >
              {accountOptions.map((opt, ind) => (
                <SimpleSelect.Option
                  key={`acct${ind}`}
                  id={`${opt.id}`}
                  value={`${opt.id}`}
                >
                  {opt.name}
                </SimpleSelect.Option>
              ))}
            </SimpleSelect>`

**Comment by atarisafari** [comment]
Thanks for the quick response! I'll double check with my user which browser + OS they are on and get back to you shortly.

**Comment by matyasf** [comment]
Hi @atarisafari!
Did you manage to test this issue?

**Comment by atarisafari** [comment]
Hey @matyasf, we did manage to do some testing and found that it was indeed working with NVDA and JAWS but was inconsistent/laggy. We think that it may be a performance issue (rather than an issue with the component or screen readers) due to the size of the list that is passed in as options to the SimpleSelect. Therefore I'll go ahead and close this ticket. 

Apologies for the late response, and thanks again for your help!
