### ISSUE TITLE
Documentation: Guide on how to add custom css

### ISSUE THREAD

**Issue by rlorenzo** [instructure/instructure-ui#98]
We want to be able to inject our own CSS in some of the components and it appears to be possible via the themable package: https://instructure.design/#themeable

But the documentation is sparse. For example, what is in styles.css? Is there a style called root? What does "CSS file must be transformed into a JS object via babel or webpack loader" mean?

Having a more fleshed out example or an example app with this implemented would be great help.

**Comment by chrisguerrero** [comment]
Hey @rlorenzo - Components made available by Instructure UI cannot be styled with custom CSS. We offer a [theme override](https://instructure.design/#ApplyTheme) system for customizing the look and feel of components. Each component documentation page contains a list of theme variables used by the component which can be overwritten.

The [ui-themeable](https://instructure.design/#ui-themeable) package can also be used to create your own custom, themed components, as described in the documentation. We also have a [starter example](https://github.com/instructure/instructure-ui-prototypes/tree/master/examples/themeable-starter) with additional information that you can try out.

**Comment by rlorenzo** [comment]
Thanks. Didn’t find https://github.com/instructure/instructure-ui-prototypes/tree/master/examples/themeable-starter before
