### ISSUE TITLE
InstUISettingsProvider missing import in CommonJS

### ISSUE THREAD

**Issue by koesie10** [instructure/instructure-ui#988]
### Background Information

**Package Version(s)**:
emotion: v8.21.0

**Browser**:
N/A

**OS:**
N/A

**Device:**
N/A

**Component**:
`InstUISettingsProvider`

### Describe the Bug

The `InstUISettingsProvider` component is missing an import for `DeterministicIdContextProvider` since v8.21.0 in the `lib` (CJS) directory. This causes our Jest tests to fail.

The commit introducing this bug is a60e3a0d. By adding the `getElementType` import, `@instructure/babel-plugin-transform-imports` will rewrite the import to:
```js
var _getElementType = require("@instructure/ui-react-utils/lib/getElementType.js");
```

It does not add an import for `DeterministicIdContextProvider`, but does use it:
```js
let providers = /*#__PURE__*/_react.default.createElement(DeterministicIdContextProvider, {
```

Before this commit, it was:
```js
var _uiReactUtils = require("@instructure/ui-react-utils");
// ...
let providers = /*#__PURE__*/_react.default.createElement(_uiReactUtils.DeterministicIdContextProvider, {
// ...
```

This happens because `@instructure/babel-plugin-transform-imports`can't find the `DeterministicIdContextProvider` at the expected import path. Therefore, it will drop the import. The warning it gives is:
```
@instructure/emotion: [cjs] [babel-plugin-transform-imports] no modules match 'DeterministicIdContextProvider' in '@instructure/ui-react-utils'. Continuing with 'DeterministicIdContextProvider' as the import path. If that is unexpected or incorrect, make sure 'DeterministicIdContextProvider' exists in '@instructure/ui-react-utils' and you have run 'yarn install' to download the package source.
```

### Steps To Reproduce
N/A

The path of the incorrect file is `packages/emotion/lib/InstUISettingsProvider/index.js`.

### Expected Behavior

There should be an import for `DeterministicIdContextProvider` or it should import and use the complete package.

### Additional Information

**Current Workaround(s):**

**Products Affected:**

**Are you willing to submit a PR to fix?**
- [ ] Yes, I'm willing to submit a PR

**Requested Priority:**

**Comment by Brailor** [comment]
Hi @koesie10!

Thank you for the detailed issue report, we are working on a fix for this and will release it asap.

**Comment by matyasf** [comment]
Hi
Thanks for the detailed report, it made the issue easy for us to fix :)
We will release the fix in a few days.
A somewhat unrelated question: We are planning to drop `CommonJS` builds in the future. Would this change cause big headaches for your product? Could you work with a pure ES6 exports InstUI?

**Comment by koesie10** [comment]
Thank you for the quick fix! We're currently only using CommonJS for our Jest tests. We can probably change our tests to using ES modules, although it seems like ES modules are still experimental in [Jest](https://jestjs.io/docs/ecmascript-modules) and [Node](https://nodejs.org/api/vm.html#vm_class_vm_module).
