### ISSUE TITLE
Applying Theme Variables

### ISSUE THREAD

**Issue by hemachand1989** [instructure/instructure-ui#99]
we want show disabled color for a Table row  "Table.Row".  Can we know how to apply theme variables with canvas theme "backgroundMedium" in case if the row is disabled. 
Currently we are using the below approach to show a disabled Row Header/Cell.

__const disabledBg = {
      background: "lightgrey",
    };
    const disabledCellTheme = Table.Cell.generateTheme("canvas", disabledBg);
    const disabledRowHeader = Table.RowHeader.generateTheme(
      "canvas",
      disabledBg
    );
and then in TableRowHeader using the disabled color
<Table.RowHeader
                      theme={disabledRowHeader}
                      >_
 Is there any straightforward approach to achieve this. Are we missing something on usage of Theme Variables. We tried documentation but the only thing we  see is ApplyTheme and when we try ApplyTheme on Table Cell it is blank .

**Comment by chrisguerrero** [comment]
Hey @hemachand1989 - You should be able to use the `theme` prop to override specific theme properties without using `generateTheme`. You can pull in the canvas theme object to use values from the global theme. Check out [this example](https://codesandbox.io/s/theme-overrides-6pc05) on Codesandbox

**Comment by hemachand1989** [comment]
Hi @chrisguerrero  , Many thanks for the snippet. Works for me.. I have a performance issue on Table component. I shall raise separate issue and would close this.
